(ns app.server-jetty
  "Electric integrated into a sample ring + jetty app."
  (:require
    [clojure.edn :as edn]
    [clojure.java.io :as io]
    [clojure.string :as str]
    [clojure.tools.logging :as log]
    [contrib.assert :refer [check]]
    [app.file-viewer :as fv]
    [app.server.rama.util-fns :as util-fns]
    [app.server.rama.objects :as rama-objects]
    [hyperfiddle.electric-ring-adapter3 :as electric-ring]
    [ring.adapter.jetty :as ring]
    [ring.middleware.content-type :refer [wrap-content-type]]
    [ring.middleware.cookies :as cookies]
    [ring.middleware.params :refer [wrap-params]]
    [ring.middleware.resource :refer [wrap-resource]]
    [ring.util.response :as res])
  (:import
    (java.util.concurrent TimeUnit)
    (org.eclipse.jetty.server.handler.gzip GzipHandler)
    (org.eclipse.jetty.websocket.server.config JettyWebSocketServletContainerInitializer JettyWebSocketServletContainerInitializer$Configurator)))

;;; Electric integration

(defn electric-websocket-middleware
  "Open a websocket and boot an Electric server program defined by `entrypoint`.
  Takes:
  - a ring handler `next-handler` to call if the request is not a websocket upgrade (e.g. the next middleware in the chain),
  - a `config` map eventually containing {:hyperfiddle.electric/user-version <version>} to ensure client and server share the same version,
    - see `hyperfiddle.electric-ring-adapter/wrap-reject-stale-client`
  - an Electric `entrypoint`: a function (fn [ring-request] (e/boot-server {} my-ns/My-e-defn ring-request))
  "
  [next-handler config entrypoint]
  ;; Applied bottom-up
  (-> (electric-ring/wrap-electric-websocket next-handler entrypoint) ; 5. connect electric client
    ; 4. this is where you would add authentication middleware (after cookie parsing, before Electric starts)
    (cookies/wrap-cookies) ; 3. makes cookies available to Electric app
    (electric-ring/wrap-reject-stale-client config) ; 2. reject stale electric client
    (wrap-params))) ; 1. parse query params

(defn get-modules [manifest-path]
  (when-let [manifest (io/resource manifest-path)]
    (let [manifest-folder (when-let [folder-name (second (rseq (str/split manifest-path #"\/")))]
                            (str "/" folder-name "/"))]
      (->> (slurp manifest)
        (edn/read-string)
        (reduce (fn [r module] (assoc r (keyword "hyperfiddle.client.module" (name (:name module)))
                                        (str manifest-folder (:output-name module)))) {})))))

(defn template
  "In string template `<div>$:foo/bar$</div>`, replace all instances of $key$
with target specified by map `m`. Target values are coerced to string with `str`.
  E.g. (template \"<div>$:foo$</div>\" {:foo 1}) => \"<div>1</div>\" - 1 is coerced to string."
  [t m] (reduce-kv (fn [acc k v] (str/replace acc (str "$" k "$") (str v))) t m))

;;; Template and serve index.html

(defn wrap-index-page
  "Server the `index.html` file with injected javascript modules from `manifest.edn`.
`manifest.edn` is generated by the client build and contains javascript modules
information."
  [next-handler config]
  (fn [ring-req]
    (if-let [response (res/resource-response (str (check string? (:resources-path config)) "/index.html"))]
      (if-let [bag (merge config (get-modules (check string? (:manifest-path config))))]
        (-> (res/response (template (slurp (:body response)) bag)) ; TODO cache in prod mode
          (res/content-type "text/html") ; ensure `index.html` is not cached
          (res/header "Cache-Control" "no-store")
          (res/header "Last-Modified" (get-in response [:headers "Last-Modified"])))
        (-> (res/not-found (pr-str ::missing-shadow-build-manifest)) ; can't inject js modules
          (res/content-type "text/plain")))
      ;; index.html file not found on classpath
      (next-handler ring-req))))

(defn not-found-handler [_ring-request]
  (-> (res/not-found "Not found")
    (res/content-type "text/plain")))

(defn json-response [data]
  (-> (res/response (pr-str data))
      (res/content-type "application/edn")))

(defn parse-edn-body
  [ring-req]
  (let [body-str (some-> ring-req :body slurp str/trim)]
    (if (str/blank? body-str)
      {}
      (edn/read-string body-str))))

(defonce !agent-runs (atom {}))

(def default-agent-timeout-ms 120000)
(def min-agent-timeout-ms 1000)
(def max-agent-timeout-ms 900000)

(defn normalize-timeout-ms
  [timeout-ms]
  (let [parsed (cond
                 (number? timeout-ms) (long timeout-ms)
                 (string? timeout-ms) (try (Long/parseLong (str/trim timeout-ms))
                                           (catch Exception _ default-agent-timeout-ms))
                 :else default-agent-timeout-ms)]
    (-> parsed
        (max min-agent-timeout-ms)
        (min max-agent-timeout-ms))))

(defn preview-str
  [x]
  (let [s (str (or x ""))]
    (if (> (count s) 180)
      (str (subs s 0 180) "...<truncated>")
      s)))

(defn summarize-agent-request
  [request-data]
  {:run-id (:run-id request-data)
   :provider (:provider request-data)
   :file (:file request-data)
   :cwd (:cwd request-data)
   :timeout-ms (:timeout-ms request-data)
   :argv (:argv request-data)
   :prompt (preview-str (:prompt request-data))
   :keys (sort (keys request-data))})

(defn start-output-reader
  [proc]
  (let [output-promise (promise)
        reader-thread (doto
                        (Thread.
                          (fn []
                            (deliver output-promise
                                     (try
                                       (slurp (.getInputStream proc))
                                       (catch Exception e
                                         (str "Failed reading process output: " (.getMessage e)))))))
                        (.setName (str "softland-agent-output-" (System/currentTimeMillis)))
                        (.setDaemon true))]
    (.start reader-thread)
    output-promise))

(defn destroy-process-tree!
  [proc]
  (try
    (doseq [child-handle (iterator-seq (.iterator (.descendants (.toHandle proc))))]
      (try
        (.destroyForcibly child-handle)
        (catch Exception _ nil)))
    (catch Exception _ nil))
  (try
    (.destroy proc)
    (catch Exception _ nil))
  (when-not (.waitFor proc 2000 TimeUnit/MILLISECONDS)
    (try
      (.destroyForcibly proc)
      (catch Exception _ nil)))
  nil)

(defn run-cli-process
  [argv cwd timeout-ms]
  (let [cmd (vec (map str argv))
        pb  (ProcessBuilder. (into-array String cmd))]
    (when (seq cwd)
      (.directory pb (io/file cwd)))
    (.redirectErrorStream pb true)
    (let [proc (.start pb)
          _ (try
              ;; Always close stdin to avoid CLIs waiting indefinitely for input.
              (.close (.getOutputStream proc))
              (catch Exception _ nil))
          output-promise (start-output-reader proc)
          finished? (.waitFor proc timeout-ms TimeUnit/MILLISECONDS)]
      (if finished?
        {:argv cmd
         :cwd cwd
         :output (deref output-promise 2000 "")
         :exit-code (.exitValue proc)
         :timed-out? false
         :timeout-ms timeout-ms}
        (do
          (destroy-process-tree! proc)
          (try
            (.close (.getInputStream proc))
            (catch Exception _ nil))
          (let [partial-output (deref output-promise 1000 "")
                timeout-msg (str "\n[Softland] Process timed out after " timeout-ms " ms and was terminated.")]
            {:argv cmd
             :cwd cwd
             :output (str partial-output timeout-msg)
             :exit-code 124
             :timed-out? true
             :timeout-ms timeout-ms}))))))

(defn run-agent-request
  [request-data]
  (let [run-id (or (:run-id request-data) (str (java.util.UUID/randomUUID)))
        provider (:provider request-data)
        prompt (:prompt request-data)
        file-path (:file request-data)
        ;; Look up stored session-id from Rama for --resume
        stored-session (when (and file-path provider)
                         (try (util-fns/get-cli-session file-path provider)
                              (catch Exception _ nil)))
        session-id (or (:session-id request-data)
                       (:session-id stored-session))
        argv (or (:argv request-data)
                 (rama-objects/provider-default-argv provider prompt session-id))
        cwd (:cwd request-data)
        timeout-ms (normalize-timeout-ms (:timeout-ms request-data))
        start-ms (System/currentTimeMillis)]
    (log/info "[AGENT][SERVER][RUN-START]"
              {:run-id run-id
               :provider provider
               :file file-path
               :cwd cwd
               :timeout-ms timeout-ms
               :argv argv
               :session-id session-id
               :prompt (preview-str prompt)})
    (swap! !agent-runs assoc run-id {:run-id run-id
                                     :status :running
                                     :provider provider
                                     :prompt prompt})
    (let [result (try
                   (run-cli-process argv cwd timeout-ms)
                   (catch Exception e
                     {:argv (vec (or argv []))
                      :cwd cwd
                      :output (str "CLI Error: " (.getMessage e))
                      :exit-code 1
                      :timed-out? false
                      :timeout-ms timeout-ms}))
          end-ms (System/currentTimeMillis)
          ;; For Claude: parse JSON output to extract session-id and clean content
          parsed (when (= provider :claude)
                   (try (rama-objects/parse-claude-json-output (:output result))
                        (catch Exception _ nil)))
          clean-output (if parsed (:content parsed) (:output result))
          new-session-id (when parsed (:session-id parsed))
          final-status (cond
                         (:timed-out? result) :timeout
                         (zero? (:exit-code result)) :complete
                         :else :failed)
          response {:run-id run-id
                    :status final-status
                    :provider provider
                    :prompt prompt
                    :result (assoc result
                                   :output clean-output
                                   :duration-ms (- end-ms start-ms))
                    :started-at start-ms
                    :ended-at end-ms}]
      ;; Store session-id in Rama for next --resume
      (when (and new-session-id file-path (= final-status :complete))
        (try
          (util-fns/update-cli-session file-path provider new-session-id)
          (catch Exception e
            (log/warn "[AGENT][SERVER][SESSION-STORE-FAILED]"
                      {:file file-path :provider provider
                       :error (.getMessage e)}))))
      (swap! !agent-runs assoc run-id response)
      (log/info "[AGENT][SERVER][RUN-END]"
                {:run-id run-id
                 :status final-status
                 :duration-ms (:duration-ms (:result response))
                 :exit-code (get-in response [:result :exit-code])
                 :timed-out? (get-in response [:result :timed-out?])
                 :timeout-ms timeout-ms
                 :session-id new-session-id})
      response)))

(defn wrap-file-api
  "Handle /api/* routes for file explorer sidebar.
   Returns EDN responses consumable by ClojureScript client."
  [next-handler]
  (fn [{:keys [uri query-params request-method] :as ring-req}]
    (case uri
      "/api/home-dirs"
      (json-response (fv/list-home-dirs))

      "/api/list-dir"
      (let [path (get query-params "path")]
        (if path
          (json-response (fv/list-directory path))
          (json-response {:error "Missing path parameter"})))

      "/api/read-file"
      (let [path (get query-params "path")
            root (get query-params "root")]
        (if (and path root)
          (json-response (fv/read-file-content path root))
          (json-response {:error "Missing path or root parameter"})))

      "/api/agent/run"
      (if (= request-method :post)
        (try
          (let [request-data (parse-edn-body ring-req)]
            (log/info "[AGENT][SERVER][HTTP-IN]"
                      {:remote-addr (:remote-addr ring-req)
                       :method request-method
                       :uri uri
                       :request (summarize-agent-request request-data)})
            (json-response (run-agent-request request-data)))
          (catch Exception e
            (log/error e "[AGENT][SERVER][HTTP-ERROR]"
                       {:remote-addr (:remote-addr ring-req)
                        :method request-method
                        :uri uri})
            (json-response {:error (str "Failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      "/api/agent/run-status"
      (let [run-id (get query-params "run-id")]
        (if (str/blank? run-id)
          (json-response {:error "Missing run-id parameter"})
          (if-let [run (get @!agent-runs run-id)]
            (json-response run)
            (json-response {:status :not-found :run-id run-id}))))

      ;; Not an API route — pass through
      (next-handler ring-req))))

(defn http-middleware [config]
  ;; these compose as functions, so are applied bottom up
  (-> not-found-handler
    (wrap-index-page config) ; 5. otherwise fallback to default page file
    (wrap-resource (:resources-path config)) ; 4. serve static file from classpath
    (wrap-content-type) ; 3. detect content (e.g. for index.html)
    (wrap-file-api) ; 2. intercept /api/* routes for file explorer
    (wrap-params))) ; 1. parse query params for API routes


(defn middleware [config entrypoint]
  (-> (http-middleware config)  ; 2. otherwise, serve regular http content
    (electric-websocket-middleware config entrypoint))) ; 1. intercept websocket upgrades and maybe start Electric

(defn- add-gzip-handler!
  "Makes Jetty server compress responses. Optional but recommended."
  [server]
  (.setHandler server
    (doto (GzipHandler.)
      #_(.setIncludedMimeTypes (into-array ["text/css" "text/plain" "text/javascript" "application/javascript" "application/json" "image/svg+xml"])) ; only compress these
      (.setMinGzipSize 1024)
      (.setHandler (.getHandler server)))))

(defn- configure-websocket!
  "Tune Jetty Websocket config for Electric compat." [server]
  (JettyWebSocketServletContainerInitializer/configure
    (.getHandler server)
    (reify JettyWebSocketServletContainerInitializer$Configurator
      (accept [_this _servletContext wsContainer]
        (.setIdleTimeout wsContainer (java.time.Duration/ofSeconds 60))
        (.setMaxBinaryMessageSize wsContainer (* 100 1024 1024)) ; 100M - temporary
        (.setMaxTextMessageSize wsContainer (* 100 1024 1024))))))   ; 100M - temporary


(defn start-server! [entrypoint
                     {:keys [port host]
                      :or   {port 8080, host "0.0.0.0"}
                      :as   config}]
  (let [server     (ring/run-jetty (middleware config entrypoint)
                     (merge {:port         port
                             :join?        false
                             :configurator (fn [server]
                                             (configure-websocket! server)
                                             (add-gzip-handler! server))}
                       config))]
    (log/info "👉" (str "http://" host ":" (-> server (.getConnectors) first (.getPort))))
    server))
