(ns app.server-jetty
  "Electric integrated into a sample ring + jetty app."
  (:require
    [clojure.edn :as edn]
    [clojure.java.io :as io]
    [clojure.string :as str]
    [clojure.tools.logging :as log]
    [contrib.assert :refer [check]]
    [app.file-viewer :as fv]
    [app.server.episode :as episode]
    [app.server.rama.cluster :as cluster]
    [app.server.review-pack :as review-pack]
    [components.adapter :as adapter]
    [components.compiler :as compiler]
    [components.token-matcher :as token-matcher]
    [components.design-tokens :as design-tokens]
    [app.server.rama.util-fns :as util-fns]
    [app.server.rama.objects :as rama-objects]
    [app.server.rama.relation-kernel :as rk]
    [app.server.env :as env]
    [clj-http.client :as http]
    [cheshire.core :as json]
    [hyperfiddle.electric-ring-adapter3 :as electric-ring]
    [ring.adapter.jetty :as ring]
    [ring.middleware.content-type :refer [wrap-content-type]]
    [ring.middleware.cookies :as cookies]
    [ring.middleware.params :refer [wrap-params]]
    [ring.middleware.resource :refer [wrap-resource]]
    [ring.core.protocols :as ring-protocols]
    [ring.util.response :as res])
  (:import
    (java.io BufferedReader InputStreamReader OutputStreamWriter)
    (java.util.concurrent TimeUnit)
    (org.eclipse.jetty.server.handler.gzip GzipHandler)
    (org.eclipse.jetty.websocket.server.config JettyWebSocketServletContainerInitializer JettyWebSocketServletContainerInitializer$Configurator)))

;;; Electric integration

(defn electric-websocket-middleware
  "Open a websocket and boot an Electric server program defined by `entrypoint`.
  Takes:
  - a ring handler `next-handler` to call if the request is not a websocket upgrade (e.g. the next middleware in the chain),
  - a `config` map eventually containing {:hyperfiddle.electric/user-version <version>} to ensure client and server share the same version,
    - see `hyperfiddle.electric-ring-adapter/wrap-reject-stale-client`
  - an Electric `entrypoint`: a function (fn [ring-request] (e/boot-server {} my-ns/My-e-defn ring-request))
  "
  [next-handler config entrypoint]
  ;; Applied bottom-up
  (-> (electric-ring/wrap-electric-websocket next-handler entrypoint) ; 5. connect electric client
    ; 4. this is where you would add authentication middleware (after cookie parsing, before Electric starts)
    (cookies/wrap-cookies) ; 3. makes cookies available to Electric app
    (electric-ring/wrap-reject-stale-client config) ; 2. reject stale electric client
    (wrap-params))) ; 1. parse query params

(defn get-modules [manifest-path]
  (when-let [manifest (io/resource manifest-path)]
    (let [manifest-folder (when-let [folder-name (second (rseq (str/split manifest-path #"\/")))]
                            (str "/" folder-name "/"))]
      (->> (slurp manifest)
        (edn/read-string)
        (reduce (fn [r module] (assoc r (keyword "hyperfiddle.client.module" (name (:name module)))
                                        (str manifest-folder (:output-name module)))) {})))))

(defn template
  "In string template `<div>$:foo/bar$</div>`, replace all instances of $key$
with target specified by map `m`. Target values are coerced to string with `str`.
  E.g. (template \"<div>$:foo$</div>\" {:foo 1}) => \"<div>1</div>\" - 1 is coerced to string."
  [t m] (reduce-kv (fn [acc k v] (str/replace acc (str "$" k "$") (str v))) t m))

;;; Template and serve index.html

(defn wrap-index-page
  "Server the `index.html` file with injected javascript modules from `manifest.edn`.
`manifest.edn` is generated by the client build and contains javascript modules
information."
  [next-handler config]
  (fn [ring-req]
    (if-let [response (res/resource-response (str (check string? (:resources-path config)) "/index.html"))]
      (if-let [bag (merge config (get-modules (check string? (:manifest-path config))))]
        (-> (res/response (template (slurp (:body response)) bag)) ; TODO cache in prod mode
          (res/content-type "text/html") ; ensure `index.html` is not cached
          (res/header "Cache-Control" "no-store")
          (res/header "Last-Modified" (get-in response [:headers "Last-Modified"])))
        (-> (res/not-found (pr-str ::missing-shadow-build-manifest)) ; can't inject js modules
          (res/content-type "text/plain")))
      ;; index.html file not found on classpath
      (next-handler ring-req))))

(defn not-found-handler [_ring-request]
  (-> (res/not-found "Not found")
    (res/content-type "text/plain")))

(defn json-response [data]
  (-> (res/response (pr-str data))
      (res/content-type "application/edn")))

(defn parse-edn-body
  [ring-req]
  (let [body-str (some-> ring-req :body slurp str/trim)]
    (if (str/blank? body-str)
      {}
      (edn/read-string body-str))))

;; =====================================================================
;; Linear API (direct GraphQL — no LLM, no MCP, no CLI)
;; =====================================================================

(def linear-teams-query
  "{ teams { nodes { id name } } }")

(def linear-viewer-query
  "{ viewer { id } }")

(def linear-issues-query
  "query($teamId: ID!, $viewerId: ID!) {
     issues(
       first: 100,
       filter: {
         team: { id: { eq: $teamId } }
         assignee: { id: { eq: $viewerId } }
         state: { type: { nin: [\"completed\", \"canceled\"] } }
       }
     ) {
       nodes {
         identifier
         title
         priority
         description
         state { name }
         assignee { name }
       }
     }
   }")

(defn linear-api-key
  []
  ;; Prefer a runtime-injected env var so local/dev secrets can stay out of the repo.
  (or (some-> (System/getenv "LINEAR_API_KEY") str/trim not-empty)
      env/linear-api-key))

(def linear-team-aliases
  {"DIS" "Discourse Graphs Team"})

(defn linear-post
  [api-key query variables]
  (http/post "https://api.linear.app/graphql"
             {:headers            {"Authorization" api-key
                                   "Content-Type"  "application/json"}
              :body               (json/generate-string
                                   {:query query
                                    :variables variables})
              :as                 :json
              :throw-exceptions   false
              :socket-timeout     10000
              :connection-timeout 5000}))

(defn linear-errors->message
  [resp fallback]
  (let [errors (get-in resp [:body :errors])]
    (if (seq errors)
      (str fallback ": "
           (str/join "; " (map #(or (:message %) (pr-str %)) errors)))
      fallback)))

(defn resolve-linear-team-id
  [api-key team-ref]
  (let [resp (linear-post api-key linear-teams-query nil)
        teams (get-in resp [:body :data :teams :nodes])
        wanted (or (get linear-team-aliases team-ref) team-ref)
        wanted-lc (some-> wanted str/lower-case)
        match (some (fn [team]
                      (let [id (:id team)
                            name (:name team)]
                        (when (or (= id wanted)
                                  (= (some-> name str/lower-case) wanted-lc))
                          team)))
                    teams)]
    (cond
      (= 200 (:status resp)) (:id match)
      :else nil)))

(defn resolve-linear-viewer-id
  [api-key]
  (let [resp (linear-post api-key linear-viewer-query nil)]
    (when (= 200 (:status resp))
      (get-in resp [:body :data :viewer :id]))))

(defn fetch-linear-issues
  "Fetch issues for a Linear team directly via GraphQL API.
   Returns {:ok true :tickets [...]} or {:ok false :error ...}."
  [team-ref]
  (let [api-key (linear-api-key)]
    (if (or (str/blank? api-key) (= api-key "YOUR_KEY_HERE"))
      {:ok false :error "Linear API key not configured. Set LINEAR_API_KEY in the server environment."}
      (try
        (if-let [team-id (resolve-linear-team-id api-key team-ref)]
          (if-let [viewer-id (resolve-linear-viewer-id api-key)]
            (let [resp (linear-post api-key linear-issues-query {:teamId team-id
                                                                 :viewerId viewer-id})
                  nodes (get-in resp [:body :data :issues :nodes])]
              (if (= 200 (:status resp))
                {:ok true
                 :tickets (mapv (fn [n]
                                  {:id          (:identifier n)
                                   :title       (:title n)
                                   :status      (get-in n [:state :name] "unknown")
                                   :assignee    (get-in n [:assignee :name] "unassigned")
                                   :priority    (:priority n 0)
                                   :description (or (:description n) "")})
                                nodes)}
                {:ok false
                 :error (linear-errors->message resp "Linear issue query failed")
                 :raw-body (:body resp)}))
            {:ok false :error "Could not resolve authenticated Linear user"})
          {:ok false
           :error (str "Linear team not found for '" team-ref "'")})
        (catch Exception e
          {:ok false :error (.getMessage e)})))))

(defonce !agent-runs (atom {}))

(def default-agent-timeout-ms 120000)
(def min-agent-timeout-ms 1000)
(def max-agent-timeout-ms 900000)

(defn normalize-timeout-ms
  [timeout-ms]
  (let [parsed (cond
                 (number? timeout-ms) (long timeout-ms)
                 (string? timeout-ms) (try (Long/parseLong (str/trim timeout-ms))
                                           (catch Exception _ default-agent-timeout-ms))
                 :else default-agent-timeout-ms)]
    (-> parsed
        (max min-agent-timeout-ms)
        (min max-agent-timeout-ms))))

(defn preview-str
  [x]
  (let [s (str (or x ""))]
    (if (> (count s) 180)
      (str (subs s 0 180) "...<truncated>")
      s)))

(defn summarize-agent-request
  [request-data]
  {:run-id (:run-id request-data)
   :provider (:provider request-data)
   :file (:file request-data)
   :cwd (:cwd request-data)
   :timeout-ms (:timeout-ms request-data)
   :argv (:argv request-data)
   :prompt (preview-str (:prompt request-data))
   :keys (sort (keys request-data))})

(defn start-output-reader
  [proc]
  (let [output-promise (promise)
        reader-thread (doto
                        (Thread.
                          (fn []
                            (deliver output-promise
                                     (try
                                       (slurp (.getInputStream proc))
                                       (catch Exception e
                                         (str "Failed reading process output: " (.getMessage e)))))))
                        (.setName (str "softland-agent-output-" (System/currentTimeMillis)))
                        (.setDaemon true))]
    (.start reader-thread)
    output-promise))

(defn destroy-process-tree!
  [proc]
  (try
    (doseq [child-handle (iterator-seq (.iterator (.descendants (.toHandle proc))))]
      (try
        (.destroyForcibly child-handle)
        (catch Exception _ nil)))
    (catch Exception _ nil))
  (try
    (.destroy proc)
    (catch Exception _ nil))
  (when-not (.waitFor proc 2000 TimeUnit/MILLISECONDS)
    (try
      (.destroyForcibly proc)
      (catch Exception _ nil)))
  nil)

(defn run-cli-process
  [argv cwd timeout-ms]
  (let [cmd (vec (map str argv))
        pb  (ProcessBuilder. (into-array String cmd))]
    (when (seq cwd)
      (.directory pb (io/file cwd)))
    (.redirectErrorStream pb true)
    (let [proc (.start pb)
          _ (try
              ;; Always close stdin to avoid CLIs waiting indefinitely for input.
              (.close (.getOutputStream proc))
              (catch Exception _ nil))
          output-promise (start-output-reader proc)
          finished? (.waitFor proc timeout-ms TimeUnit/MILLISECONDS)]
      (if finished?
        {:argv cmd
         :cwd cwd
         :output (deref output-promise 2000 "")
         :exit-code (.exitValue proc)
         :timed-out? false
         :timeout-ms timeout-ms}
        (do
          (destroy-process-tree! proc)
          (try
            (.close (.getInputStream proc))
            (catch Exception _ nil))
          (let [partial-output (deref output-promise 1000 "")
                timeout-msg (str "\n[Softland] Process timed out after " timeout-ms " ms and was terminated.")]
            {:argv cmd
             :cwd cwd
             :output (str partial-output timeout-msg)
             :exit-code 124
             :timed-out? true
             :timeout-ms timeout-ms}))))))

(defn run-agent-request
  [request-data]
  (let [run-id (or (:run-id request-data) (str (java.util.UUID/randomUUID)))
        provider (:provider request-data)
        prompt (:prompt request-data)
        file-path (:file request-data)
        ;; Look up stored session-id from Rama for --resume
        stored-session (when (and file-path provider)
                         (try (util-fns/get-cli-session file-path provider)
                              (catch Exception _ nil)))
        session-id (or (:session-id request-data)
                       (:session-id stored-session))
        argv (or (:argv request-data)
                 (rama-objects/provider-default-argv provider prompt session-id))
        cwd (:cwd request-data)
        timeout-ms (normalize-timeout-ms (:timeout-ms request-data))
        start-ms (System/currentTimeMillis)]
    (log/info "[AGENT][SERVER][RUN-START]"
              {:run-id run-id
               :provider provider
               :file file-path
               :cwd cwd
               :timeout-ms timeout-ms
               :argv argv
               :session-id session-id
               :prompt (preview-str prompt)})
    (swap! !agent-runs assoc run-id {:run-id run-id
                                     :status :running
                                     :provider provider
                                     :prompt prompt})
    (let [result (try
                   (run-cli-process argv cwd timeout-ms)
                   (catch Exception e
                     {:argv (vec (or argv []))
                      :cwd cwd
                      :output (str "CLI Error: " (.getMessage e))
                      :exit-code 1
                      :timed-out? false
                      :timeout-ms timeout-ms}))
          end-ms (System/currentTimeMillis)
          ;; For Claude: parse JSON output to extract session-id and clean content
          parsed (when (= provider :claude)
                   (try (rama-objects/parse-claude-json-output (:output result))
                        (catch Exception _ nil)))
          clean-output (if parsed (:content parsed) (:output result))
          new-session-id (when parsed (:session-id parsed))
          final-status (cond
                         (:timed-out? result) :timeout
                         (zero? (:exit-code result)) :complete
                         :else :failed)
          response {:run-id run-id
                    :status final-status
                    :provider provider
                    :prompt prompt
                    :result (assoc result
                                   :output clean-output
                                   :duration-ms (- end-ms start-ms))
                    :started-at start-ms
                    :ended-at end-ms}]
      ;; Store session-id in Rama for next --resume
      (when (and new-session-id file-path (= final-status :complete))
        (try
          (util-fns/update-cli-session file-path provider new-session-id)
          (catch Exception e
            (log/warn "[AGENT][SERVER][SESSION-STORE-FAILED]"
                      {:file file-path :provider provider
                       :error (.getMessage e)}))))
      (swap! !agent-runs assoc run-id response)
      (log/info "[AGENT][SERVER][RUN-END]"
                {:run-id run-id
                 :status final-status
                 :duration-ms (:duration-ms (:result response))
                 :exit-code (get-in response [:result :exit-code])
                 :timed-out? (get-in response [:result :timed-out?])
                 :timeout-ms timeout-ms
                 :session-id new-session-id})
      response)))

;;; ── Streaming agent execution (SSE over POST) ──────────────────────────────

(defn stream-cli-process
  "Spawn a CLI process and read its stdout line-by-line.
   Calls (on-line line-str) for each line, (on-done info-map) when the process
   exits or times out. Runs reader + waiter on daemon threads."
  [argv cwd timeout-ms on-line on-done]
  (let [cmd  (vec (map str argv))
        pb   (ProcessBuilder. (into-array String cmd))]
    (when (seq cwd)
      (.directory pb (io/file cwd)))
    (.redirectErrorStream pb true)
    (let [proc       (.start pb)
          _          (try (.close (.getOutputStream proc)) (catch Exception _ nil))
          start-ms   (System/currentTimeMillis)
          reader     (BufferedReader. (InputStreamReader. (.getInputStream proc)))
          ;; Reader thread: emit lines until EOF
          read-thread
          (doto (Thread.
                  (fn []
                    (try
                      (loop []
                        (when-let [line (.readLine reader)]
                          (try (on-line line) (catch Exception _ nil))
                          (recur)))
                      (catch Exception e
                        (log/debug "[STREAM] reader exception" (.getMessage e)))
                      (finally
                        (try (.close reader) (catch Exception _ nil))))))
            (.setName (str "stream-reader-" (System/currentTimeMillis)))
            (.setDaemon true))
          ;; Waiter thread: wait for exit or timeout, then invoke on-done
          wait-thread
          (doto (Thread.
                  (fn []
                    (let [finished? (.waitFor proc timeout-ms TimeUnit/MILLISECONDS)
                          end-ms    (System/currentTimeMillis)]
                      (if finished?
                        (do (.join read-thread 2000) ;; let reader drain
                            (on-done {:exit-code   (.exitValue proc)
                                      :timed-out?  false
                                      :duration-ms (- end-ms start-ms)}))
                        (do (destroy-process-tree! proc)
                            (try (.close (.getInputStream proc)) (catch Exception _ nil))
                            (.join read-thread 1000)
                            (on-done {:exit-code   124
                                      :timed-out?  true
                                      :duration-ms (- end-ms start-ms)}))))))
            (.setName (str "stream-waiter-" (System/currentTimeMillis)))
            (.setDaemon true))]
      (.start read-thread)
      (.start wait-thread)
      proc)))

(defn parse-stream-json-line
  "Parse a single NDJSON line from `claude --output-format stream-json --include-partial-messages`.
   Event types:
     system       → {:session_id ...}
     stream_event → wraps Anthropic API events (content_block_delta, etc.)
     assistant    → full message (ignored — we already got deltas)
     result       → {:session_id ... :total_cost_usd ...}"
  [line]
  (let [mk-event (fn [kind payload]
                   (assoc payload
                          :kind kind
                          :event kind
                          :ts (System/currentTimeMillis)))]
    (try
      (let [obj (json/parse-string line true)]
        (case (:type obj)
          ;; system line carries session-id; model as :run-start envelope.
          "system"
          (mk-event :run-start {:session-id (:session_id obj)})

          "stream_event"
          (let [inner (:event obj)]
            (case (:type inner)
              "content_block_delta"
              (let [delta (:delta inner)
                    idx   (:index inner)]
                (cond
                  (= (:type delta) "text_delta")
                  (mk-event :text-delta {:text (:text delta)})

                  (= (:type delta) "input_json_delta")
                  (mk-event :tool-input-delta
                            {:block-idx idx
                             :json-chunk (:partial_json delta)})

                  (= (:type delta) "thinking_delta")
                  (mk-event :thinking-delta {:text (:thinking delta)})

                  (= (:type delta) "signature_delta")
                  nil  ;; verification signature — not needed for display

                  :else nil))

              "content_block_start"
              (let [block (:content_block inner)
                    idx   (:index inner)]
                (cond
                  (= (:type block) "tool_use")
                  (mk-event :tool-use-start
                            {:block-idx idx
                             :tool-id (:id block)
                             :tool-name (:name block)})

                  (= (:type block) "tool_result")
                  (mk-event :tool-result
                            {:block-idx idx
                             :tool-id (:tool_use_id block)
                             :content (:content block)})

                  (= (:type block) "thinking")
                  (mk-event :thinking-start {:block-idx idx})

                  :else nil))

              "content_block_stop"
              (mk-event :block-stop {:block-idx (:index inner)})

              ;; message_start, message_delta, message_stop — skip
              nil))

          ;; assistant — full message; fallback if --include-partial-messages wasn't passed
          "assistant"
          (let [text (->> (get-in obj [:message :content])
                          (filter #(= (:type %) "text"))
                          (map :text)
                          (str/join "\n"))]
            (when (seq text)
              (mk-event :text-delta {:text text})))

          "result"
          (mk-event :run-done
                    {:status :complete
                     :session-id (:session_id obj)
                     :cost-usd (:total_cost_usd obj)
                     :result (:result obj)})

          ;; Unknown types — skip
          nil))
      (catch Exception e
        (mk-event :run-error
                  {:error :invalid-json-line
                   :message (.getMessage e)
                   :raw (preview-str line)})))))

(defn initial-stream-state []
  {:tool-ids #{}
   :tool-by-block {}
   :terminal-kind nil
   :saw-run-start? false})

(defn apply-stream-invariants
  "Validate and enrich one parsed stream event.
   Returns [next-state maybe-emit-event]."
  [state evt]
  (let [mk-error (fn [payload]
                   [(assoc state :terminal-kind :run-error)
                    (assoc payload
                           :kind :run-error
                           :event :run-error
                           :ts (System/currentTimeMillis))])]
    (cond
      (:terminal-kind state)
      [state nil]

      (or (nil? (:kind evt)) (nil? (:ts evt)))
      (mk-error {:error :invalid-envelope
                 :details (dissoc evt :ts)})

      (= :run-start (:kind evt))
      [(assoc state :saw-run-start? true) evt]

      (= :tool-use-start (:kind evt))
      (let [tool-id (:tool-id evt)
            block-idx (:block-idx evt)]
        (if (or (nil? tool-id) (str/blank? (str tool-id)))
          (mk-error {:error :tool-use-missing-id
                     :block-idx block-idx})
          [(-> state
               (update :tool-ids conj tool-id)
               (assoc-in [:tool-by-block block-idx] tool-id))
           evt]))

      (= :tool-input-delta (:kind evt))
      (let [tool-id (or (:tool-id evt)
                        (get-in state [:tool-by-block (:block-idx evt)]))]
        (if (contains? (:tool-ids state) tool-id)
          [state (assoc evt :tool-id tool-id)]
          (mk-error {:error :unknown-tool-reference
                     :source-kind :tool-input-delta
                     :tool-id tool-id
                     :block-idx (:block-idx evt)})))

      (= :tool-result (:kind evt))
      (let [tool-id (:tool-id evt)]
        (if (contains? (:tool-ids state) tool-id)
          [state evt]
          (mk-error {:error :unknown-tool-reference
                     :source-kind :tool-result
                     :tool-id tool-id
                     :block-idx (:block-idx evt)})))

      (= :run-done (:kind evt))
      [(assoc state :terminal-kind :run-done) evt]

      (= :run-error (:kind evt))
      [(assoc state :terminal-kind :run-error) evt]

      :else
      [state evt])))

(defn parse-stream-json-lines
  "Parse + validate a sequence of raw NDJSON lines, returning normalized events."
  [lines]
  (let [{:keys [events state]}
        (reduce (fn [{:keys [events state]} line]
                  (if-let [evt (parse-stream-json-line line)]
                    (let [[state* emit] (apply-stream-invariants state evt)]
                      {:events (cond-> events emit (conj emit))
                       :state state*})
                    {:events events :state state}))
                {:events [] :state (initial-stream-state)}
                lines)]
    (if (:terminal-kind state)
      events
      (conj events
            {:kind :run-error
             :event :run-error
             :ts (System/currentTimeMillis)
             :error :missing-terminal-event}))))

(defn write-event!
  "Write one SSE event as `data: {edn}\\n\\n` and flush."
  [^java.io.Writer writer evt]
  (.write writer (str "data: " (pr-str evt) "\n\n"))
  (.flush writer))

(defn run-agent-stream
  "Streaming variant of run-agent-request. Returns a Ring response with
   Content-Type text/event-stream. Each SSE event is an EDN map."
  [request-data]
  (let [run-id      (or (:run-id request-data) (str (java.util.UUID/randomUUID)))
        provider    (:provider request-data)
        prompt      (:prompt request-data)
        file-path   (:file request-data)
        stored-ses  (when (and file-path provider)
                      (try (util-fns/get-cli-session file-path provider)
                           (catch Exception _ nil)))
        session-id  (or (:session-id request-data)
                        (:session-id stored-ses))
        allowed-tools (:allowed-tools request-data)
        json-schema       (:json-schema request-data)
        max-budget-usd    (:max-budget-usd request-data)
        model             (:model request-data)
        append-sys-prompt (:append-system-prompt request-data)
        argv        (or (:argv request-data)
                        (rama-objects/provider-default-argv
                          provider prompt session-id
                          :output-format (if (= provider :claude) "stream-json" nil)
                          :include-partials? (= provider :claude)
                          :allowed-tools allowed-tools
                          :json-schema json-schema
                          :max-budget-usd max-budget-usd
                          :model model
                          :append-system-prompt append-sys-prompt))
        cwd         (:cwd request-data)
        timeout-ms  (normalize-timeout-ms (:timeout-ms request-data))
        ;; Capture session-id from stream events
        !session-id (atom session-id)]
    {:status  200
     :headers {"Content-Type"       "text/event-stream"
               "Cache-Control"      "no-cache"
               "X-Accel-Buffering"  "no"
               "Connection"         "keep-alive"}
     :body
     (reify ring-protocols/StreamableResponseBody
       (write-body-to-stream [_ _response output-stream]
         (let [writer (OutputStreamWriter. output-stream "UTF-8")]
           (try
             (let [!stream-state (atom (initial-stream-state))]
               ;; Non-Claude providers have no stream-json envelope, so emit run-start upfront.
               (when (not= provider :claude)
                 (let [[state* evt]
                       (apply-stream-invariants @!stream-state
                                                {:kind :run-start
                                                 :event :run-start
                                                 :ts (System/currentTimeMillis)
                                                 :run-id run-id
                                                 :provider provider
                                                 :prompt prompt
                                                 :argv argv
                                                 :session-id session-id})]
                   (reset! !stream-state state*)
                   (when evt
                     (write-event! writer evt))))
             (let [done-promise (promise)]
               (stream-cli-process
                 argv cwd timeout-ms
                 ;; on-line callback
                 (fn [line]
                   (if (= provider :claude)
                     (when-let [evt0 (parse-stream-json-line line)]
                       (when-let [sid (:session-id evt0)]
                         (reset! !session-id sid))
                       (let [evt1 (if (= :run-start (:kind evt0))
                                    (merge {:run-id run-id
                                            :provider provider
                                            :prompt prompt
                                            :argv argv}
                                           evt0)
                                    evt0)
                             [state* evt] (apply-stream-invariants @!stream-state evt1)]
                         (reset! !stream-state state*)
                         (when evt
                           (write-event! writer evt))))
                     (let [[state* evt]
                           (apply-stream-invariants @!stream-state
                                                    {:kind :text-delta
                                                     :event :text-delta
                                                     :ts (System/currentTimeMillis)
                                                     :text (str line "\n")})]
                       (reset! !stream-state state*)
                       (when evt
                         (write-event! writer evt)))))
                 ;; on-done callback
                 (fn [{:keys [exit-code timed-out? duration-ms]}]
                   (let [status (cond timed-out? :timeout
                                      (zero? exit-code) :complete
                                      :else :failed)
                         terminal? (:terminal-kind @!stream-state)]
                     ;; Emit exactly one terminal event.
                     (when-not terminal?
                       (let [terminal-evt (if (= status :complete)
                                            {:kind :run-done
                                             :event :run-done
                                             :ts (System/currentTimeMillis)
                                             :status status
                                             :exit-code exit-code
                                             :duration-ms duration-ms}
                                            {:kind :run-error
                                             :event :run-error
                                             :ts (System/currentTimeMillis)
                                             :status status
                                             :exit-code exit-code
                                             :duration-ms duration-ms
                                             :error (if timed-out?
                                                      :timeout
                                                      :process-failed)})
                             [state* emit] (apply-stream-invariants @!stream-state terminal-evt)]
                         (reset! !stream-state state*)
                         (when emit
                           (write-event! writer emit))))
                     ;; Persist session-id to Rama
                     (let [final-sid @!session-id]
                       (when (and final-sid file-path (= status :complete))
                         (try
                           (util-fns/update-cli-session file-path provider final-sid)
                           (catch Exception e
                             (log/warn "[AGENT][STREAM][SESSION-STORE-FAILED]"
                                       {:error (.getMessage e)})))))
                     (deliver done-promise true))))
               ;; Block this thread until process completes — keeps stream open
               @done-promise))
             (catch Exception e
               (println "[STREAM][ERROR]" (.getMessage e)))
             (finally
               (try (.flush writer) (catch Exception _ nil))
               (try (.close writer) (catch Exception _ nil)))))))}))

;;; ── first-light A P2b · the episode turn (SSE over POST) ───────────────────
;;
;; The ground's send lane (CONTRACT §7 P2b addressing): Ctrl+Enter fires from
;; the FOCUSED block, whose content is ALREADY durable (birthed + committed-
;; echo edits — the P2 client-buffer mint is dead). What becomes durable HERE,
;; BEFORE the agent spawns, is the revision-pinned TURN RECORD: source-block-id
;; + the pinned content (text + kernel hash) + send-time position — later
;; edits or moves never rewrite what the resident answered. Event order:
;;   :episode-durable   — the turn record is acked (append+await), BEFORE the
;;                        agent is spawned (the durable-BEFORE-agent law,
;;                        unchanged)
;;   <claude stream events> — the resident agent's live turn (the existing CLI
;;                        lane; subscription auth, zero keys)
;;   :run-done/:run-error   — the turn closes honestly (timeout/failed named)
;;   :episode-distilled — post-turn harvest+distill receipt (T8; G4); the
;;                        ingest epoch bump makes the worn face re-pull TRUTH
;; The turn cell's status is overwritten :open → :complete/:failed/:timeout at
;; turn end; an abrupt JVM death leaves :open — the honest open fact (G4b).
;; A failed turn-record mint emits :run-error and never spawns the agent.

(defn run-episode-turn
  "POST /api/episode/utterance {:source-unit-id :content-text :position
   :turn-id :time-ms :prev-turn-id} → SSE. turn-id + time-ms are CLIENT-minted
   once per Ctrl+Enter (the wear-id precedent) so an HTTP retry re-derives
   identical import identity and the journal no-ops — never a double turn."
  [request-data]
  (let [text           (str (:content-text request-data))
        source-unit-id (:source-unit-id request-data)
        position       (:position request-data)
        turn-id        (str (:turn-id request-data))
        time-ms        (long (or (:time-ms request-data) (System/currentTimeMillis)))
        prev-turn-id   (:prev-turn-id request-data)
        cwd            (str (or (:cwd request-data) (System/getProperty "user.dir")))
        timeout-ms     (long (or (:timeout-ms request-data) 600000))
        ;; drill seam (G3/G4/G4b): a machinery drill names its OWN episode so
        ;; the GENESIS first utterance stays Sid's act (§11). The ground client
        ;; never sends this; nil = the genesis episode.
        conv-id        (:conversation-id request-data)
        ;; one canvas, many conversations: :thread-id scopes the CLI SESSION
        ;; (and its jsonl/distill container) while conv-id keeps naming the
        ;; canvas container where turn records land. Absent = the genesis
        ;; thread — session and container coincide, the pre-thread behavior.
        thread-id      (some-> (:thread-id request-data) str not-empty)
        session-id     (or thread-id conv-id)]
    {:status  200
     :headers {"Content-Type"      "text/event-stream"
               "Cache-Control"     "no-cache"
               "X-Accel-Buffering" "no"
               "Connection"        "keep-alive"}
     :body
     (reify ring-protocols/StreamableResponseBody
       (write-body-to-stream [_ _response output-stream]
         (let [writer (OutputStreamWriter. output-stream "UTF-8")]
           (try
             (let [oc-rt (:oc-rt (fv/face-ctx))]
               (if (or (str/blank? text) (str/blank? turn-id)
                       (str/blank? (str source-unit-id)) (nil? oc-rt))
                 (write-event! writer {:kind :run-error :event :run-error
                                       :ts (System/currentTimeMillis)
                                       :error (cond (nil? oc-rt) :land-unavailable
                                                    (str/blank? text) :empty-utterance
                                                    (str/blank? (str source-unit-id)) :missing-source-block
                                                    :else :missing-turn-id)})
                 (let [durable (try
                                 (episode/record-turn!
                                  oc-rt {:turn-id turn-id
                                         :source-unit-id source-unit-id
                                         :content-text text
                                         :position position
                                         :status :open
                                         :time-ms time-ms :prev-turn-id prev-turn-id
                                         :conversation-id conv-id
                                         :thread-id thread-id})
                                 (catch Exception e
                                   {:status :error :error (.getMessage e)}))]
                   (if-not (= :accepted (:status durable))
                     (write-event! writer {:kind :run-error :event :run-error
                                           :ts (System/currentTimeMillis)
                                           :error :turn-not-durable
                                           :detail (dissoc durable :decision)})
                     (do
                       (write-event! writer {:kind :episode-durable :event :episode-durable
                                             :ts (System/currentTimeMillis)
                                             :turn-id turn-id
                                             :source-unit-id source-unit-id
                                             :address (:address durable)
                                             :import-key (:import-key durable)})
                       (let [!stream-state (atom (initial-stream-state))
                             done-promise  (promise)
                             argv (episode/summon-argv {:cwd cwd :prompt text
                                                        :conversation-id session-id})]
                         (log/info "[EPISODE][TURN-START]"
                                   {:turn-id turn-id :argv argv :cwd cwd
                                    :thread-id thread-id})
                         (stream-cli-process
                          argv cwd timeout-ms
                          (fn [line]
                            (when-let [evt0 (parse-stream-json-line line)]
                              (let [[state* evt] (apply-stream-invariants @!stream-state evt0)]
                                (reset! !stream-state state*)
                                (when evt (write-event! writer evt)))))
                          (fn [{:keys [exit-code timed-out? duration-ms]}]
                            (let [status (cond timed-out? :timeout
                                               (zero? exit-code) :complete
                                               :else :failed)]
                              (when-not (:terminal-kind @!stream-state)
                                (let [terminal-evt (if (= status :complete)
                                                     {:kind :run-done :event :run-done
                                                      :ts (System/currentTimeMillis)
                                                      :status status :exit-code exit-code
                                                      :duration-ms duration-ms}
                                                     {:kind :run-error :event :run-error
                                                      :ts (System/currentTimeMillis)
                                                      :status status :exit-code exit-code
                                                      :duration-ms duration-ms
                                                      :error (if timed-out? :timeout :process-failed)})
                                      [state* emit] (apply-stream-invariants @!stream-state terminal-evt)]
                                  (reset! !stream-state state*)
                                  (when emit (write-event! writer emit))))
                              ;; the turn cell's status overwrite (:open →
                              ;; :complete/:failed/:timeout) — best-effort; a
                              ;; failure here leaves the honest :open fact
                              (try
                                (episode/record-turn!
                                 oc-rt {:turn-id turn-id
                                        :source-unit-id source-unit-id
                                        :content-text text
                                        :position position
                                        :status status
                                        :time-ms time-ms :prev-turn-id prev-turn-id
                                        :conversation-id conv-id
                                        :thread-id thread-id})
                                (catch Exception e
                                  (log/warn "[EPISODE][TURN-STATUS-FAILED]"
                                            {:turn-id turn-id :error (.getMessage e)})))
                              ;; post-turn distill runs on the waiter thread —
                              ;; the stream stays open until the receipt lands.
                              ;; It harvests the SESSION's jsonl into the
                              ;; session's own container (identity follows the
                              ;; line's sessionId by design) — the serve merge
                              ;; reads it back into the canvas.
                              (let [distill (try
                                              (episode/post-turn-distill!
                                               oc-rt {:cwd cwd :conversation-id session-id})
                                              (catch Exception e
                                                {:status :distill-failed :error (.getMessage e)}))]
                                (log/info "[EPISODE][TURN-DISTILLED]"
                                          {:turn-id turn-id
                                           :status (:status distill)
                                           :river (:river distill)
                                           :native (:native distill)})
                                (write-event! writer
                                              {:kind :episode-distilled :event :episode-distilled
                                               :ts (System/currentTimeMillis)
                                               :status (:status distill)
                                               :river (:river distill)
                                               :native (:native distill)
                                               :debris (:debris distill)
                                               :error (:error distill)}))
                              (deliver done-promise true))))
                         @done-promise))))))
             (catch Exception e
               (println "[EPISODE][STREAM-ERROR]" (.getMessage e)))
             (finally
               (try (.flush writer) (catch Exception _ nil))
               (try (.close writer) (catch Exception _ nil)))))))}))

;; =====================================================================
;; Relation /assert write shim — git-spine WP2 component W (CONTRACT §3.E).
;;
;; POST /api/relation/assert is the land's first write affordance (D-008): a CLI
;; agent asserts a RelationEdge via `curl`. The route validates route-side, does
;; WRITE-AHEAD durability (one plain-map line, flushed) BEFORE appending the
;; envelope to the running trail runtime's relation depot, and returns
;; {relation-id request-id}. Boot replay of that log is P1's job (git_spine.clj);
;; the two components meet ONLY at the file format + path, so this file NEVER
;; requires git_spine (SF-R2.1) — it derives the shared path from a local
;; constant, identically to P1.
;; =====================================================================

(defn edn-response
  "EDN response map with an explicit HTTP status (mirrors json-response's
   application/edn content-type). Real 4xx/5xx status codes, unlike the legacy
   always-200 json-response helper."
  ([data] (edn-response 200 data))
  ([status data]
   {:status  status
    :headers {"Content-Type" "application/edn"}
    :body    (pr-str data)}))

(def assert-log-relative-path
  "Repo-root-relative path of the shared relation-assert write-ahead log
   (CONTRACT §3.C/§3.E, pinned by SF-R2.1). This route (PW) and the boot
   replayer (P1) each derive the identical absolute path from this constant with
   ZERO shared code and no dependency on the git_spine namespace."
  "data/relation-assert-log.ednl")

(defn default-assert-log-path
  "Absolute assert-log path anchored at the repo root (user.dir), matching
   file_viewer's boot-cfg root idiom. Computed at request time only; the parent
   dir is created at runtime by the writer, never pre-created in the tree."
  []
  (str (System/getProperty "user.dir") "/" assert-log-relative-path))

(def relation-target-kind-allowlist
  "Route-side target-kind allowlist (CONTRACT §3.E / validator A4): the kernel
   exports no target-kind validator and ->target-ref never throws, so the route
   guards the joinable kinds explicitly. :git-commit is deliberately ABSENT
   (gate review 2026-07-05): its target-key derives as the BARE sha
   (relation_kernel ->target-ref), which can never join the RENDERED commit
   object (keyed on its oc:doc container id) — the exact non-join CONTRACT
   v1.1 removed from the import path (§2.3). Assert about a commit as
   :container + the commit's oc:doc:<key> id, which View-3 prints."
  #{:container :source :doc-file :conversation})

(defn validate-assert-params
  "nil when `params` is a valid assert; else {:reason <string>} naming the first
   failure. Guards (CONTRACT §3.E): kind ∈ rk/relation-kinds; from/to kinds ∈ the
   route-side target allowlist; from/to ids are non-blank strings; asserter-id a
   non-blank string and asserter-type a keyword (gate review 2026-07-05: the
   depot rejects a nil :actor/id AFTER the route would have 200'd — the route
   must never 200 a request it can know the depot will reject, nor write-ahead
   a poison line that re-fails on every boot replay)."
  [{:keys [kind from-kind from-id to-kind to-id asserter-id asserter-type]}]
  (cond
    (not (contains? rk/relation-kinds kind))
    {:reason (str "unknown relation kind " (pr-str kind)
                  "; expected one of " (pr-str (vec (sort rk/relation-kinds))))}

    (not (contains? relation-target-kind-allowlist from-kind))
    {:reason (str "from-kind " (pr-str from-kind) " not in allowlist "
                  (pr-str (vec (sort relation-target-kind-allowlist))))}

    (not (contains? relation-target-kind-allowlist to-kind))
    {:reason (str "to-kind " (pr-str to-kind) " not in allowlist "
                  (pr-str (vec (sort relation-target-kind-allowlist))))}

    (not (rk/present-string? from-id))
    {:reason "from-id must be a non-blank string"}

    (not (rk/present-string? to-id))
    {:reason "to-id must be a non-blank string"}

    (not (rk/present-string? asserter-id))
    {:reason "asserter-id must be a non-blank string (custody: who asserts this?)"}

    (not (keyword? asserter-type))
    {:reason "asserter-type must be a keyword, e.g. :human :agent :import"}

    :else nil))

(defn envelope->plain-map
  "Convert an assert envelope to a pure-EDN plain map for the write-ahead log
   (CONTRACT §3.C): the :payload record and its nested :from/:to target-ref
   records become plain maps (`into {}`, recursive). Every other envelope value is
   already EDN, so the line pr-str's tag-free and round-trips through
   clojure.edn/read-string."
  [envelope]
  (let [ref->map (fn [ref] (when ref (into {} ref)))]
    (update envelope :payload
            (fn [payload]
              (-> (into {} payload)
                  (update :from ref->map)
                  (update :to ref->map))))))

(def ^:private assert-log-lock
  "Serializes assert-log appends so concurrent /assert POSTs (multiple curl
   agents, D-008) cannot interleave bytes and corrupt a line — every line must
   round-trip through clojure.edn/read-string on replay. In-process monitor; the
   endpoint is low-frequency so contention is negligible."
  (Object.))

(defn append-assert-log-line!
  "Write-ahead durability (CONTRACT §3.E): append ONE pr-str'd plain-map line to
   the assert-log, creating the parent dir at runtime (never pre-created in the
   tree) and flushing per append. `request` is a relation envelope.

   *print-namespace-maps* is bound false so the :actor submap prints as explicit
   {:actor/id .. :actor/type ..} rather than the #:actor{..} namespace-map
   shorthand — the line then contains NO '#' at all (no ambiguity vs reader
   tags), and clojure.edn/read-string reads both forms identically, so P1's
   replayer is unaffected."
  [log-path request]
  (let [f    (io/file log-path)
        ;; pure work off the lock: build the whole line first
        line (binding [*print-namespace-maps* false]
               (pr-str (envelope->plain-map request)))]
    (io/make-parents f)
    (locking assert-log-lock
      ;; UTF-8 pinned on BOTH sides of the seam (replay reader pins it too):
      ;; the JVM default charset flipped at Java 18 (JEP 400), and a non-ASCII
      ;; :note must replay identically on a host with a different file.encoding.
      (with-open [w (io/writer f :append true :encoding "UTF-8")]
        (.write w line)
        (.write w "\n")
        (.flush w)))))

(defn assert-relation-handler
  "git-spine WP2 component W core. Validates route-side, then on success does
   WRITE-AHEAD (one durable plain-map line) BEFORE appending the envelope to the
   trail runtime's relation depot; returns a ring response. Decoupled from HTTP
   routing + runtime resolution so tests (and the final-phase G8 pair test) drive
   it directly with a test runtime + tmp log path.

   opts   {:runtime <relation runtime handle> :log-path <assert-log path string>}
   params {:kind :from-kind :from-id :to-kind :to-id :note :asserter-id
           :asserter-type + optional :idempotency-key}

   Idempotency (gate review 2026-07-05, trap-4 parity with the import path):
   the default request-id/idempotency-key is the DETERMINISTIC
   \"assert:<relation-id>\" — a curl retry after a timeout re-sends the same
   key, the journal drops the replay, and NO duplicate decision/event/activity
   rows accrue. An optional :idempotency-key param overrides it for the
   deliberate re-assert case (e.g. after a retract, or to update :note), where
   the journal must NOT drop the request.

   Valid   → write log line, append to depot, 200 {:ok true :relation-id :request-id}.
   Invalid → 400 {:ok false :reason ...}; NO file write, NO depot append."
  [{:keys [runtime log-path]} params]
  (if-let [{:keys [reason]} (validate-assert-params params)]
    (edn-response 400 {:ok false :error :invalid-request :reason reason})
    (let [{:keys [kind from-kind from-id to-kind to-id note asserter-id asserter-type]} params
          from-ref    (rk/->target-ref from-kind from-id)
          to-ref      (rk/->target-ref to-kind to-id)
          relation-id (rk/relation-id-for kind from-ref to-ref asserter-id)
          ;; blank/non-string overrides fall through to the default — a blank
          ;; key would be depot-rejected AFTER the 200 (the poison-line class)
          request-id  (if (rk/present-string? (:idempotency-key params))
                        (:idempotency-key params)
                        (str "assert:" relation-id))
          request     (rk/assert-request
                       {:kind kind :from from-ref :to to-ref
                        :asserter-actor-id asserter-id
                        :asserter-type asserter-type
                        :asserted-at-ms (System/currentTimeMillis)
                        :request-id request-id
                        :idempotency-key request-id
                        :note note})]
      ;; write-ahead FIRST: if the log write throws, the depot is never touched.
      ;; durable-ground P4: a nil log-path means the WAL is OFF (cluster mode —
      ;; the depot append below IS the durable log); the depot ack replaces the
      ;; write-ahead line, not the other way around.
      (when log-path
        (append-assert-log-line! log-path request))
      (rk/append-relation-request! runtime request)
      (edn-response 200 {:ok true
                         :relation-id (rk/relreq-routing-key request)
                         :request-id request-id}))))

(defn resolve-trail-runtime-or-503
  "Obtain the trail runtime from its defonce delay WITHOUT ever triggering cluster
   boot from a probe (CONTRACT §3.E / validator A3). Returns [:ok runtime] or
   [:unavailable reason]. An unrealized delay is reported unavailable and is NEVER
   forced; a realized deref is wrapped in a ~2s-timeout future so a pathological
   deref returns unavailable instead of hanging."
  [rt-delay]
  (if-not (realized? rt-delay)
    [:unavailable "trail runtime not booted"]
    (let [fut (future @rt-delay)]
      (try
        (let [rt (deref fut 2000 ::timeout)]
          (if (= rt ::timeout)
            (do (future-cancel fut) [:unavailable "trail runtime not booted"])
            [:ok rt]))
        (catch Exception _
          (future-cancel fut)
          [:unavailable "trail runtime not booted"])))))

(defn handle-assert-route
  "Route composition for POST /api/relation/assert: resolve the runtime from
   `rt-delay` (503 if not booted, never booting it), parse the EDN body, and
   delegate to assert-relation-handler with the shared log path. Takes rt-delay +
   log-path as args so the 503 branch is testable without the real defonce."
  [ring-req rt-delay log-path]
  (let [[status runtime] (resolve-trail-runtime-or-503 rt-delay)]
    (if (= status :ok)
      (assert-relation-handler {:runtime runtime :log-path log-path}
                               (parse-edn-body ring-req))
      (edn-response 503 {:ok false :error :runtime-unavailable
                         :message "trail runtime not booted"}))))

(defn wrap-file-api
  "Handle /api/* routes for file explorer sidebar.
   Returns EDN responses consumable by ClojureScript client."
  [next-handler]
  (fn [{:keys [uri query-params request-method] :as ring-req}]
    (cond
      ;; ===== Relation assert (/assert write shim — git-spine WP2 component W) =====
      (= uri "/api/relation/assert")
      (if (= request-method :post)
        (try
          (handle-assert-route ring-req fv/trail-runtime-ref
                               ;; durable-ground P4: cluster mode writes no
                               ;; assert WAL — the relation depot is the log.
                               (when-not (cluster/cluster-boot?)
                                 (default-assert-log-path)))
          (catch Exception e
            (log/error e "[RELATION][ASSERT][ERROR]" {:uri uri})
            (edn-response 500 {:ok false :error :server-error
                               :message (str "assert failed: " (.getMessage e))})))
        (edn-response 405 {:ok false :error :method-not-allowed
                           :message "Method not allowed. Use POST."}))

      ;; ===== Review Pack API =====
      (= uri "/api/review-pack/create")
      (if (= request-method :post)
        (try
          (json-response (review-pack/create-review-pack! (parse-edn-body ring-req)))
          (catch Exception e
            (log/error e "[REVIEW-PACK][CREATE][ERROR]" {:uri uri})
            (json-response {:ok false
                            :error :server-error
                            :message (str "Failed creating review pack: " (.getMessage e))})))
        (json-response {:ok false :error :method-not-allowed :message "Method not allowed. Use POST."}))

      (= uri "/api/review-pack/list")
      (if (= request-method :get)
        (json-response {:ok true :review-packs (review-pack/list-review-packs)})
        (json-response {:ok false :error :method-not-allowed :message "Method not allowed. Use GET."}))

      (re-matches #"/api/review-pack/([^/]+)/publish" uri)
      (let [[_ pack-id] (re-matches #"/api/review-pack/([^/]+)/publish" uri)]
        (if (= request-method :post)
          (try
            (json-response (review-pack/publish-review-pack! pack-id (parse-edn-body ring-req)))
            (catch Exception e
              (log/error e "[REVIEW-PACK][PUBLISH][ERROR]" {:pack-id pack-id})
              (json-response {:ok false
                              :error :server-error
                              :message (str "Failed publishing review pack: " (.getMessage e))})))
          (json-response {:ok false :error :method-not-allowed :message "Method not allowed. Use POST."})))

      (re-matches #"/api/review-pack/([^/]+)/summary" uri)
      (let [[_ pack-id] (re-matches #"/api/review-pack/([^/]+)/summary" uri)
            base-url (or (get query-params "base-url") "")]
        (if (= request-method :get)
          (json-response (review-pack/review-pack-summary pack-id {:base-url base-url}))
          (json-response {:ok false :error :method-not-allowed :message "Method not allowed. Use GET."})))

      (re-matches #"/api/review-pack/([^/]+)/feedback" uri)
      (let [[_ pack-id] (re-matches #"/api/review-pack/([^/]+)/feedback" uri)]
        (if (= request-method :post)
          (try
            (json-response (review-pack/add-feedback! pack-id (parse-edn-body ring-req)))
            (catch Exception e
              (log/error e "[REVIEW-PACK][FEEDBACK][ERROR]" {:pack-id pack-id})
              (json-response {:ok false
                              :error :server-error
                              :message (str "Failed adding feedback: " (.getMessage e))})))
          (json-response {:ok false :error :method-not-allowed :message "Method not allowed. Use POST."})))

      (re-matches #"/api/review-pack/([^/]+)" uri)
      (let [[_ pack-id] (re-matches #"/api/review-pack/([^/]+)" uri)]
        (if (= request-method :get)
          (if-let [pack (review-pack/get-review-pack pack-id)]
            (json-response {:ok true :pack pack})
            (json-response {:ok false :error :not-found :message "Review pack not found"}))
          (json-response {:ok false :error :method-not-allowed :message "Method not allowed. Use GET."})))

      ;; ===== Component Library Registry =====
      (= uri "/api/components/registry")
      (try
        (let [base-dir (io/file "components")
              registry-file (io/file base-dir "_registry.edn")
              registry (when (.exists registry-file)
                         (edn/read-string (slurp registry-file)))
              ;; Read _source.edn for each component to get current status
              components (mapv (fn [{:keys [slug] :as comp}]
                                (let [source-file (io/file base-dir slug "_source.edn")
                                      source (when (.exists source-file)
                                               (edn/read-string (slurp source-file)))
                                      ;; Check if .cljc file exists for shadcn
                                      cljc-file (io/file base-dir slug "shadcn.cljc")
                                      has-cljc? (.exists cljc-file)]
                                  (assoc comp
                                    :source source
                                    :has-cljc? has-cljc?)))
                              (:components registry))]
          (json-response {:ok true
                          :libraries (:libraries registry)
                          :components components}))
        (catch Exception e
          (log/error e "[COMPONENTS] registry read failed")
          (json-response {:ok false :error (.getMessage e)})))

      ;; Update component status (after conversion)
      (= uri "/api/components/status")
      (if (= request-method :post)
        (try
          (let [body (parse-edn-body ring-req)
                slug (:slug body)
                library (or (:library body) :shadcn-v4)
                status (or (:status body) :ready)
                source-file (io/file "components" slug "_source.edn")]
            (if (.exists source-file)
              (let [source (edn/read-string (slurp source-file))
                    updated (-> source
                                (assoc-in [library :status] status)
                                (assoc-in [library :converted] (str (java.time.LocalDate/now))))]
                (spit source-file (pr-str updated))
                (json-response {:ok true :slug slug :status status}))
              (json-response {:ok false :error "Component not found"})))
          (catch Exception e
            (log/error e "[COMPONENTS] status update failed")
            (json-response {:ok false :error (.getMessage e)})))
        (json-response {:ok false :error "POST required"}))

      ;; ===== Linear API (direct, no LLM) =====
      (= uri "/api/linear/issues")
      (let [team-key (or (get query-params "team") "DIS")]
        (json-response (fetch-linear-issues team-key)))

      ;; ===== Design Converter API =====
      (= uri "/api/extract/compile")
      (if (= request-method :post)
        (try
          (let [request-data (parse-edn-body ring-req)
                extracted-tree (:tree request-data)
                source-url (or (:source-url request-data) "")
                dt design-tokens/dt
                ;; Step 1: extracted JSON → Design IR
                ir (adapter/extracted->ir extracted-tree {:source-url source-url})
                ;; Step 2: tokenize (snap to dt)
                tokenized-ir (token-matcher/tokenize-ir ir dt)
                ;; Step 3: compile to rt-node
                rt-node (compiler/compile-ir tokenized-ir dt {:use-tokens? true})]
            (json-response {:ok true
                            :ir tokenized-ir
                            :rt-node rt-node
                            :source-url source-url}))
          (catch Exception e
            (log/error e "[EXTRACT] compile failed")
            (json-response {:ok false :error (.getMessage e)})))
        (json-response {:ok false :error "POST required"}))

      ;; ===== Sidebar Rama Actions =====
      (= uri "/api/sidebar/action")
      (if (= request-method :post)
        (try
          (let [body (parse-edn-body ring-req)
                action-type (:action-type body)
                data (or (:data body) {})]
            (json-response (util-fns/emit-sidebar-event! action-type data)))
          (catch Exception e
            (log/error e "[SIDEBAR][ACTION][ERROR]")
            (json-response {:error (str "Sidebar action failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      (= uri "/api/sidebar/state")
      (json-response (util-fns/get-sidebar-state))

      ;; ===== Settings Rama Actions =====
      (= uri "/api/settings/update")
      (if (= request-method :post)
        (try
          (let [body (parse-edn-body ring-req)
                settings-data (or (:data body) {})]
            (json-response (util-fns/emit-settings-event! settings-data)))
          (catch Exception e
            (log/error e "[SETTINGS][UPDATE][ERROR]")
            (json-response {:error (str "Settings update failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      (= uri "/api/settings/state")
      (json-response (util-fns/get-settings-state))

      ;; ===== Agent Trail Persistence =====
      (= uri "/api/agent/trail/save")
      (if (= request-method :post)
        (try
          (let [body (parse-edn-body ring-req)
                run-id (:run-id body)
                trail-data (:trail-data body)]
            (if (and run-id trail-data)
              (json-response (util-fns/save-agent-trail! run-id trail-data))
              (json-response {:error "Missing run-id or trail-data"})))
          (catch Exception e
            (log/error e "[AGENT-TRAIL][SAVE][ERROR]")
            (json-response {:error (str "Trail save failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      ;; ===== Workspace Truth Persistence (Phase 7) =====
      (= uri "/api/workspace/save-truth")
      (if (= request-method :post)
        (try
          (let [body (parse-edn-body ring-req)
                truth-data (or (:data body) {})]
            (json-response (util-fns/emit-workspace-truth-event! truth-data)))
          (catch Exception e
            (log/error e "[WORKSPACE][SAVE][ERROR]")
            (json-response {:error (str "Workspace save failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      ;; ===== Editor State Persistence (Phase 4B measurement) =====
      (= uri "/api/editor/save-doc")
      (if (= request-method :post)
        (try
          (let [body (parse-edn-body ring-req)
                file-path (:file-path body)
                doc-state (:doc-state body)]
            (if (and file-path doc-state)
              (json-response (util-fns/save-editor-doc! file-path doc-state))
              (json-response {:error "Missing file-path or doc-state"})))
          (catch Exception e
            (log/error e "[EDITOR][SAVE][ERROR]")
            (json-response {:error (str "Editor save failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      ;; ===== Flow Session Persistence =====
      (= uri "/api/flow/save-state")
      (if (= request-method :post)
        (try
          (let [body (parse-edn-body ring-req)
                flow-data (or (:data body) {})]
            (json-response (util-fns/emit-flow-session-event! flow-data)))
          (catch Exception e
            (log/error e "[FLOW][SAVE][ERROR]")
            (json-response {:error (str "Flow save failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      ;; ===== Existing File/Agent API =====
      (= uri "/api/home-dirs")
      (json-response (fv/list-home-dirs))

      (= uri "/api/list-dir")
      (let [path (get query-params "path")]
        (if path
          (json-response (fv/list-directory path))
          (json-response {:error "Missing path parameter"})))

      (= uri "/api/read-file")
      (let [path (get query-params "path")
            root (get query-params "root")]
        (if (and path root)
          (json-response (fv/read-file-content path root))
          (json-response {:error "Missing path or root parameter"})))

      (= uri "/api/agent/run")
      (if (= request-method :post)
        (try
          (let [request-data (parse-edn-body ring-req)]
            (log/info "[AGENT][SERVER][HTTP-IN]"
                      {:remote-addr (:remote-addr ring-req)
                       :method request-method
                       :uri uri
                       :request (summarize-agent-request request-data)})
            (json-response (run-agent-request request-data)))
          (catch Exception e
            (log/error e "[AGENT][SERVER][HTTP-ERROR]"
                       {:remote-addr (:remote-addr ring-req)
                        :method request-method
                        :uri uri})
            (json-response {:error (str "Failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      (= uri "/api/agent/stream")
      (if (= request-method :post)
        (try
          (let [request-data (parse-edn-body ring-req)]
            (log/info "[AGENT][STREAM][HTTP-IN]"
                      {:remote-addr (:remote-addr ring-req)
                       :request (summarize-agent-request request-data)})
            (run-agent-stream request-data))
          (catch Exception e
            (log/error e "[AGENT][STREAM][HTTP-ERROR]"
                       {:remote-addr (:remote-addr ring-req) :uri uri})
            (json-response {:error (str "Stream failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      ;; first-light A P2 — the ground's one lane (T9: Ctrl+Enter lands here)
      (= uri "/api/episode/utterance")
      (if (= request-method :post)
        (try
          (let [request-data (parse-edn-body ring-req)]
            (log/info "[EPISODE][HTTP-IN]"
                      {:remote-addr (:remote-addr ring-req)
                       :turn-id (:turn-id request-data)
                       :chars (count (str (:text request-data)))})
            (run-episode-turn request-data))
          (catch Exception e
            (log/error e "[EPISODE][HTTP-ERROR]"
                       {:remote-addr (:remote-addr ring-req) :uri uri})
            (json-response {:error (str "Episode turn failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      ;; first-light A P2b — block birth: the FIRST content act mints the
      ;; durable block at the chosen point (unit + birth-position geometry
      ;; cell in ONE acked import — §5.1 lane; block-id + time-ms are
      ;; CLIENT-minted once, so retries converge). Escape before content
      ;; never reaches here — no unit is ever minted for an abandoned anchor.
      (= uri "/api/episode/block-birth")
      (if (= request-method :post)
        (try
          (let [{:keys [block-id text time-ms position conversation-id]}
                (parse-edn-body ring-req)
                oc-rt (:oc-rt (fv/face-ctx))]
            (if (or (nil? oc-rt) (str/blank? (str block-id)) (nil? text))
              (edn-response 400 {:status :rejected
                                 :error (if (nil? oc-rt) :land-unavailable :bad-request)})
              (let [r (episode/append-utterance!
                       oc-rt {:text (str text) :turn-id (str block-id)
                              :time-ms (long (or time-ms (System/currentTimeMillis)))
                              :position position
                              :conversation-id conversation-id})]
                (when (= :accepted (:status r))
                  ;; the mint IS an ingest (INV-19) — the face re-pull is the
                  ;; committed-echo cross-check channel
                  (swap! util-fns/!ingest-epoch-atom inc))
                (edn-response (if (= :accepted (:status r)) 200 409)
                              (dissoc r :decision)))))
          (catch Exception e
            (log/error e "[EPISODE][BIRTH-ERROR]" {:uri uri})
            (edn-response 500 {:status :error :error (.getMessage e)})))
        (edn-response 405 {:error "Method not allowed. Use POST."}))

      ;; first-light A P2b — the geometry settle write: camera + block
      ;; positions as SETTLE-STATE truth (one acked write per gesture burst,
      ;; never per-event; the ack IS the safety mechanism). Hint-only import,
      ;; settled cells (P2B.md receipt a). No epoch bump — geometry changes
      ;; no served block material.
      (= uri "/api/episode/geometry")
      (if (= request-method :post)
        (try
          (let [{:keys [cells camera settle-id time-ms conversation-id]}
                (parse-edn-body ring-req)
                oc-rt (:oc-rt (fv/face-ctx))]
            (if (or (nil? oc-rt) (str/blank? (str settle-id))
                    (and (empty? cells) (nil? camera)))
              (edn-response 400 {:status :rejected
                                 :error (if (nil? oc-rt) :land-unavailable :bad-request)})
              (let [r (episode/settle-geometry!
                       oc-rt {:cells (vec cells) :camera camera
                              :settle-id (str settle-id)
                              :time-ms (long (or time-ms (System/currentTimeMillis)))
                              :conversation-id conversation-id})]
                (edn-response (if (= :accepted (:status r)) 200 409)
                              (dissoc r :decision)))))
          (catch Exception e
            (log/error e "[EPISODE][GEOMETRY-ERROR]" {:uri uri})
            (edn-response 500 {:status :error :error (.getMessage e)})))
        (edn-response 405 {:error "Method not allowed. Use POST."}))

      (= uri "/api/agent/run-status")
      (let [run-id (get query-params "run-id")]
        (if (str/blank? run-id)
          (json-response {:error "Missing run-id parameter"})
          (if-let [run (get @!agent-runs run-id)]
            (json-response run)
            (json-response {:status :not-found :run-id run-id}))))

      (= uri "/api/dev/replay-fixture")
      (try
        (let [file (io/file "test/fixtures/claude-stream-sample.jsonl")]
          (if (.exists file)
            (let [lines (with-open [rdr (io/reader file)]
                          (doall (line-seq rdr)))
                  events (parse-stream-json-lines lines)]
              (json-response {:ok true :events events}))
            (json-response {:ok false :error "Fixture not found"})))
        (catch Exception e
          (json-response {:ok false :error (.getMessage e)})))

      :else
      ;; Not an API route — pass through
      (next-handler ring-req))))

(defn http-middleware [config]
  ;; these compose as functions, so are applied bottom up
  (-> not-found-handler
    (wrap-index-page config) ; 5. otherwise fallback to default page file
    (wrap-resource (:resources-path config)) ; 4. serve static file from classpath
    (wrap-content-type) ; 3. detect content (e.g. for index.html)
    (wrap-file-api) ; 2. intercept /api/* routes for file explorer
    (wrap-params))) ; 1. parse query params for API routes


(defn middleware [config entrypoint]
  (-> (http-middleware config)  ; 2. otherwise, serve regular http content
    (electric-websocket-middleware config entrypoint))) ; 1. intercept websocket upgrades and maybe start Electric

(defn- add-gzip-handler!
  "Makes Jetty server compress responses. Optional but recommended."
  [server]
  (.setHandler server
    (doto (GzipHandler.)
      #_(.setIncludedMimeTypes (into-array ["text/css" "text/plain" "text/javascript" "application/javascript" "application/json" "image/svg+xml"])) ; only compress these
      (.setMinGzipSize 1024)
      (.setHandler (.getHandler server)))))

(defn- configure-websocket!
  "Tune Jetty Websocket config for Electric compat." [server]
  (JettyWebSocketServletContainerInitializer/configure
    (.getHandler server)
    (reify JettyWebSocketServletContainerInitializer$Configurator
      (accept [_this _servletContext wsContainer]
        (.setIdleTimeout wsContainer (java.time.Duration/ofSeconds 60))
        (.setMaxBinaryMessageSize wsContainer (* 100 1024 1024)) ; 100M - temporary
        (.setMaxTextMessageSize wsContainer (* 100 1024 1024))))))   ; 100M - temporary


(defn start-server! [entrypoint
                     {:keys [port host]
                      :or   {port 8080, host "0.0.0.0"}
                      :as   config}]
  (let [server     (ring/run-jetty (middleware config entrypoint)
                     (merge {:port         port
                             :join?        false
                             :configurator (fn [server]
                                             (configure-websocket! server)
                                             (add-gzip-handler! server))}
                       config))]
    (log/info "👉" (str "http://" host ":" (-> server (.getConnectors) first (.getPort))))
    server))
