(ns app.server-jetty
  "Electric integrated into a sample ring + jetty app."
  (:require
    [clojure.edn :as edn]
    [clojure.java.io :as io]
    [clojure.string :as str]
    [clojure.tools.logging :as log]
    [contrib.assert :refer [check]]
    [app.file-viewer :as fv]
    [app.server.rama.util-fns :as util-fns]
    [app.server.rama.objects :as rama-objects]
    [cheshire.core :as json]
    [hyperfiddle.electric-ring-adapter3 :as electric-ring]
    [ring.adapter.jetty :as ring]
    [ring.middleware.content-type :refer [wrap-content-type]]
    [ring.middleware.cookies :as cookies]
    [ring.middleware.params :refer [wrap-params]]
    [ring.middleware.resource :refer [wrap-resource]]
    [ring.core.protocols :as ring-protocols]
    [ring.util.response :as res])
  (:import
    (java.io BufferedReader InputStreamReader OutputStreamWriter)
    (java.util.concurrent TimeUnit)
    (org.eclipse.jetty.server.handler.gzip GzipHandler)
    (org.eclipse.jetty.websocket.server.config JettyWebSocketServletContainerInitializer JettyWebSocketServletContainerInitializer$Configurator)))

;;; Electric integration

(defn electric-websocket-middleware
  "Open a websocket and boot an Electric server program defined by `entrypoint`.
  Takes:
  - a ring handler `next-handler` to call if the request is not a websocket upgrade (e.g. the next middleware in the chain),
  - a `config` map eventually containing {:hyperfiddle.electric/user-version <version>} to ensure client and server share the same version,
    - see `hyperfiddle.electric-ring-adapter/wrap-reject-stale-client`
  - an Electric `entrypoint`: a function (fn [ring-request] (e/boot-server {} my-ns/My-e-defn ring-request))
  "
  [next-handler config entrypoint]
  ;; Applied bottom-up
  (-> (electric-ring/wrap-electric-websocket next-handler entrypoint) ; 5. connect electric client
    ; 4. this is where you would add authentication middleware (after cookie parsing, before Electric starts)
    (cookies/wrap-cookies) ; 3. makes cookies available to Electric app
    (electric-ring/wrap-reject-stale-client config) ; 2. reject stale electric client
    (wrap-params))) ; 1. parse query params

(defn get-modules [manifest-path]
  (when-let [manifest (io/resource manifest-path)]
    (let [manifest-folder (when-let [folder-name (second (rseq (str/split manifest-path #"\/")))]
                            (str "/" folder-name "/"))]
      (->> (slurp manifest)
        (edn/read-string)
        (reduce (fn [r module] (assoc r (keyword "hyperfiddle.client.module" (name (:name module)))
                                        (str manifest-folder (:output-name module)))) {})))))

(defn template
  "In string template `<div>$:foo/bar$</div>`, replace all instances of $key$
with target specified by map `m`. Target values are coerced to string with `str`.
  E.g. (template \"<div>$:foo$</div>\" {:foo 1}) => \"<div>1</div>\" - 1 is coerced to string."
  [t m] (reduce-kv (fn [acc k v] (str/replace acc (str "$" k "$") (str v))) t m))

;;; Template and serve index.html

(defn wrap-index-page
  "Server the `index.html` file with injected javascript modules from `manifest.edn`.
`manifest.edn` is generated by the client build and contains javascript modules
information."
  [next-handler config]
  (fn [ring-req]
    (if-let [response (res/resource-response (str (check string? (:resources-path config)) "/index.html"))]
      (if-let [bag (merge config (get-modules (check string? (:manifest-path config))))]
        (-> (res/response (template (slurp (:body response)) bag)) ; TODO cache in prod mode
          (res/content-type "text/html") ; ensure `index.html` is not cached
          (res/header "Cache-Control" "no-store")
          (res/header "Last-Modified" (get-in response [:headers "Last-Modified"])))
        (-> (res/not-found (pr-str ::missing-shadow-build-manifest)) ; can't inject js modules
          (res/content-type "text/plain")))
      ;; index.html file not found on classpath
      (next-handler ring-req))))

(defn not-found-handler [_ring-request]
  (-> (res/not-found "Not found")
    (res/content-type "text/plain")))

(defn json-response [data]
  (-> (res/response (pr-str data))
      (res/content-type "application/edn")))

(defn parse-edn-body
  [ring-req]
  (let [body-str (some-> ring-req :body slurp str/trim)]
    (if (str/blank? body-str)
      {}
      (edn/read-string body-str))))

(defonce !agent-runs (atom {}))

(def default-agent-timeout-ms 120000)
(def min-agent-timeout-ms 1000)
(def max-agent-timeout-ms 900000)

(defn normalize-timeout-ms
  [timeout-ms]
  (let [parsed (cond
                 (number? timeout-ms) (long timeout-ms)
                 (string? timeout-ms) (try (Long/parseLong (str/trim timeout-ms))
                                           (catch Exception _ default-agent-timeout-ms))
                 :else default-agent-timeout-ms)]
    (-> parsed
        (max min-agent-timeout-ms)
        (min max-agent-timeout-ms))))

(defn preview-str
  [x]
  (let [s (str (or x ""))]
    (if (> (count s) 180)
      (str (subs s 0 180) "...<truncated>")
      s)))

(defn summarize-agent-request
  [request-data]
  {:run-id (:run-id request-data)
   :provider (:provider request-data)
   :file (:file request-data)
   :cwd (:cwd request-data)
   :timeout-ms (:timeout-ms request-data)
   :argv (:argv request-data)
   :prompt (preview-str (:prompt request-data))
   :keys (sort (keys request-data))})

(defn start-output-reader
  [proc]
  (let [output-promise (promise)
        reader-thread (doto
                        (Thread.
                          (fn []
                            (deliver output-promise
                                     (try
                                       (slurp (.getInputStream proc))
                                       (catch Exception e
                                         (str "Failed reading process output: " (.getMessage e)))))))
                        (.setName (str "softland-agent-output-" (System/currentTimeMillis)))
                        (.setDaemon true))]
    (.start reader-thread)
    output-promise))

(defn destroy-process-tree!
  [proc]
  (try
    (doseq [child-handle (iterator-seq (.iterator (.descendants (.toHandle proc))))]
      (try
        (.destroyForcibly child-handle)
        (catch Exception _ nil)))
    (catch Exception _ nil))
  (try
    (.destroy proc)
    (catch Exception _ nil))
  (when-not (.waitFor proc 2000 TimeUnit/MILLISECONDS)
    (try
      (.destroyForcibly proc)
      (catch Exception _ nil)))
  nil)

(defn run-cli-process
  [argv cwd timeout-ms]
  (let [cmd (vec (map str argv))
        pb  (ProcessBuilder. (into-array String cmd))]
    (when (seq cwd)
      (.directory pb (io/file cwd)))
    (.redirectErrorStream pb true)
    (let [proc (.start pb)
          _ (try
              ;; Always close stdin to avoid CLIs waiting indefinitely for input.
              (.close (.getOutputStream proc))
              (catch Exception _ nil))
          output-promise (start-output-reader proc)
          finished? (.waitFor proc timeout-ms TimeUnit/MILLISECONDS)]
      (if finished?
        {:argv cmd
         :cwd cwd
         :output (deref output-promise 2000 "")
         :exit-code (.exitValue proc)
         :timed-out? false
         :timeout-ms timeout-ms}
        (do
          (destroy-process-tree! proc)
          (try
            (.close (.getInputStream proc))
            (catch Exception _ nil))
          (let [partial-output (deref output-promise 1000 "")
                timeout-msg (str "\n[Softland] Process timed out after " timeout-ms " ms and was terminated.")]
            {:argv cmd
             :cwd cwd
             :output (str partial-output timeout-msg)
             :exit-code 124
             :timed-out? true
             :timeout-ms timeout-ms}))))))

(defn run-agent-request
  [request-data]
  (let [run-id (or (:run-id request-data) (str (java.util.UUID/randomUUID)))
        provider (:provider request-data)
        prompt (:prompt request-data)
        file-path (:file request-data)
        ;; Look up stored session-id from Rama for --resume
        stored-session (when (and file-path provider)
                         (try (util-fns/get-cli-session file-path provider)
                              (catch Exception _ nil)))
        session-id (or (:session-id request-data)
                       (:session-id stored-session))
        argv (or (:argv request-data)
                 (rama-objects/provider-default-argv provider prompt session-id))
        cwd (:cwd request-data)
        timeout-ms (normalize-timeout-ms (:timeout-ms request-data))
        start-ms (System/currentTimeMillis)]
    (log/info "[AGENT][SERVER][RUN-START]"
              {:run-id run-id
               :provider provider
               :file file-path
               :cwd cwd
               :timeout-ms timeout-ms
               :argv argv
               :session-id session-id
               :prompt (preview-str prompt)})
    (swap! !agent-runs assoc run-id {:run-id run-id
                                     :status :running
                                     :provider provider
                                     :prompt prompt})
    (let [result (try
                   (run-cli-process argv cwd timeout-ms)
                   (catch Exception e
                     {:argv (vec (or argv []))
                      :cwd cwd
                      :output (str "CLI Error: " (.getMessage e))
                      :exit-code 1
                      :timed-out? false
                      :timeout-ms timeout-ms}))
          end-ms (System/currentTimeMillis)
          ;; For Claude: parse JSON output to extract session-id and clean content
          parsed (when (= provider :claude)
                   (try (rama-objects/parse-claude-json-output (:output result))
                        (catch Exception _ nil)))
          clean-output (if parsed (:content parsed) (:output result))
          new-session-id (when parsed (:session-id parsed))
          final-status (cond
                         (:timed-out? result) :timeout
                         (zero? (:exit-code result)) :complete
                         :else :failed)
          response {:run-id run-id
                    :status final-status
                    :provider provider
                    :prompt prompt
                    :result (assoc result
                                   :output clean-output
                                   :duration-ms (- end-ms start-ms))
                    :started-at start-ms
                    :ended-at end-ms}]
      ;; Store session-id in Rama for next --resume
      (when (and new-session-id file-path (= final-status :complete))
        (try
          (util-fns/update-cli-session file-path provider new-session-id)
          (catch Exception e
            (log/warn "[AGENT][SERVER][SESSION-STORE-FAILED]"
                      {:file file-path :provider provider
                       :error (.getMessage e)}))))
      (swap! !agent-runs assoc run-id response)
      (log/info "[AGENT][SERVER][RUN-END]"
                {:run-id run-id
                 :status final-status
                 :duration-ms (:duration-ms (:result response))
                 :exit-code (get-in response [:result :exit-code])
                 :timed-out? (get-in response [:result :timed-out?])
                 :timeout-ms timeout-ms
                 :session-id new-session-id})
      response)))

;;; ── Streaming agent execution (SSE over POST) ──────────────────────────────

(defn stream-cli-process
  "Spawn a CLI process and read its stdout line-by-line.
   Calls (on-line line-str) for each line, (on-done info-map) when the process
   exits or times out. Runs reader + waiter on daemon threads."
  [argv cwd timeout-ms on-line on-done]
  (let [cmd  (vec (map str argv))
        pb   (ProcessBuilder. (into-array String cmd))]
    (when (seq cwd)
      (.directory pb (io/file cwd)))
    (.redirectErrorStream pb true)
    (let [proc       (.start pb)
          _          (try (.close (.getOutputStream proc)) (catch Exception _ nil))
          start-ms   (System/currentTimeMillis)
          reader     (BufferedReader. (InputStreamReader. (.getInputStream proc)))
          ;; Reader thread: emit lines until EOF
          read-thread
          (doto (Thread.
                  (fn []
                    (try
                      (loop []
                        (when-let [line (.readLine reader)]
                          (try (on-line line) (catch Exception _ nil))
                          (recur)))
                      (catch Exception e
                        (log/debug "[STREAM] reader exception" (.getMessage e)))
                      (finally
                        (try (.close reader) (catch Exception _ nil))))))
            (.setName (str "stream-reader-" (System/currentTimeMillis)))
            (.setDaemon true))
          ;; Waiter thread: wait for exit or timeout, then invoke on-done
          wait-thread
          (doto (Thread.
                  (fn []
                    (let [finished? (.waitFor proc timeout-ms TimeUnit/MILLISECONDS)
                          end-ms    (System/currentTimeMillis)]
                      (if finished?
                        (do (.join read-thread 2000) ;; let reader drain
                            (on-done {:exit-code   (.exitValue proc)
                                      :timed-out?  false
                                      :duration-ms (- end-ms start-ms)}))
                        (do (destroy-process-tree! proc)
                            (try (.close (.getInputStream proc)) (catch Exception _ nil))
                            (.join read-thread 1000)
                            (on-done {:exit-code   124
                                      :timed-out?  true
                                      :duration-ms (- end-ms start-ms)}))))))
            (.setName (str "stream-waiter-" (System/currentTimeMillis)))
            (.setDaemon true))]
      (.start read-thread)
      (.start wait-thread)
      proc)))

(defn parse-stream-json-line
  "Parse a single NDJSON line from `claude --output-format stream-json --include-partial-messages`.
   Event types:
     system       → {:session_id ...}
     stream_event → wraps Anthropic API events (content_block_delta, etc.)
     assistant    → full message (ignored — we already got deltas)
     result       → {:session_id ... :total_cost_usd ...}"
  [line]
  (try
    (let [obj (json/parse-string line true)]
      (case (:type obj)
        "system"
        {:event :init :session-id (:session_id obj)}

        "stream_event"
        (let [inner (:event obj)]
          (case (:type inner)
            "content_block_delta"
            (when-let [text (get-in inner [:delta :text])]
              {:event :text-delta :text text})
            ;; message_start, content_block_start/stop, message_delta, message_stop — skip
            nil))

        ;; assistant — full message; fallback if --include-partial-messages wasn't passed
        "assistant"
        (let [text (->> (get-in obj [:message :content])
                        (filter #(= (:type %) "text"))
                        (map :text)
                        (str/join "\n"))]
          (when (seq text)
            {:event :text-delta :text text}))

        "result"
        {:event :result
         :session-id (:session_id obj)
         :cost-usd (:total_cost_usd obj)}

        ;; Unknown types — skip
        nil))
    (catch Exception _
      nil)))

(defn write-event!
  "Write one SSE event as `data: {edn}\\n\\n` and flush."
  [^java.io.Writer writer evt]
  (.write writer (str "data: " (pr-str evt) "\n\n"))
  (.flush writer))

(defn run-agent-stream
  "Streaming variant of run-agent-request. Returns a Ring response with
   Content-Type text/event-stream. Each SSE event is an EDN map."
  [request-data]
  (let [run-id      (or (:run-id request-data) (str (java.util.UUID/randomUUID)))
        provider    (:provider request-data)
        prompt      (:prompt request-data)
        file-path   (:file request-data)
        stored-ses  (when (and file-path provider)
                      (try (util-fns/get-cli-session file-path provider)
                           (catch Exception _ nil)))
        session-id  (or (:session-id request-data)
                        (:session-id stored-ses))
        argv        (or (:argv request-data)
                        (rama-objects/provider-default-argv
                          provider prompt session-id
                          :output-format (if (= provider :claude) "stream-json" nil)
                          :include-partials? (= provider :claude)))
        cwd         (:cwd request-data)
        timeout-ms  (normalize-timeout-ms (:timeout-ms request-data))
        ;; Capture session-id from stream events
        !session-id (atom session-id)]
    {:status  200
     :headers {"Content-Type"       "text/event-stream"
               "Cache-Control"      "no-cache"
               "X-Accel-Buffering"  "no"
               "Connection"         "keep-alive"}
     :body
     (reify ring-protocols/StreamableResponseBody
       (write-body-to-stream [_ _response output-stream]
         (let [writer (OutputStreamWriter. output-stream "UTF-8")]
           (try
             ;; Send :start event immediately — flushes to Jetty's output
             (write-event! writer {:event    :start
                                   :run-id   run-id
                                   :provider provider
                                   :prompt   prompt})
             (let [done-promise (promise)]
               (stream-cli-process
                 argv cwd timeout-ms
                 ;; on-line callback
                 (fn [line]
                   (if (= provider :claude)
                     (when-let [evt (parse-stream-json-line line)]
                       (when-let [sid (:session-id evt)]
                         (reset! !session-id sid))
                       (write-event! writer evt))
                     (write-event! writer {:event :text-delta :text (str line "\n")})))
                 ;; on-done callback
                 (fn [{:keys [exit-code timed-out? duration-ms]}]
                   (let [status (cond timed-out? :timeout
                                      (zero? exit-code) :complete
                                      :else :failed)]
                     (write-event! writer {:event       :done
                                           :status      status
                                           :exit-code   exit-code
                                           :duration-ms duration-ms})
                     ;; Persist session-id to Rama
                     (let [final-sid @!session-id]
                       (when (and final-sid file-path (= status :complete))
                         (try
                           (util-fns/update-cli-session file-path provider final-sid)
                           (catch Exception e
                             (log/warn "[AGENT][STREAM][SESSION-STORE-FAILED]"
                                       {:error (.getMessage e)})))))
                     (deliver done-promise true))))
               ;; Block this thread until process completes — keeps stream open
               @done-promise)
             (catch Exception e
               (println "[STREAM][ERROR]" (.getMessage e)))
             (finally
               (try (.flush writer) (catch Exception _ nil))
               (try (.close writer) (catch Exception _ nil)))))))}))

(defn wrap-file-api
  "Handle /api/* routes for file explorer sidebar.
   Returns EDN responses consumable by ClojureScript client."
  [next-handler]
  (fn [{:keys [uri query-params request-method] :as ring-req}]
    (case uri
      "/api/home-dirs"
      (json-response (fv/list-home-dirs))

      "/api/list-dir"
      (let [path (get query-params "path")]
        (if path
          (json-response (fv/list-directory path))
          (json-response {:error "Missing path parameter"})))

      "/api/read-file"
      (let [path (get query-params "path")
            root (get query-params "root")]
        (if (and path root)
          (json-response (fv/read-file-content path root))
          (json-response {:error "Missing path or root parameter"})))

      "/api/agent/run"
      (if (= request-method :post)
        (try
          (let [request-data (parse-edn-body ring-req)]
            (log/info "[AGENT][SERVER][HTTP-IN]"
                      {:remote-addr (:remote-addr ring-req)
                       :method request-method
                       :uri uri
                       :request (summarize-agent-request request-data)})
            (json-response (run-agent-request request-data)))
          (catch Exception e
            (log/error e "[AGENT][SERVER][HTTP-ERROR]"
                       {:remote-addr (:remote-addr ring-req)
                        :method request-method
                        :uri uri})
            (json-response {:error (str "Failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      "/api/agent/stream"
      (if (= request-method :post)
        (try
          (let [request-data (parse-edn-body ring-req)]
            (log/info "[AGENT][STREAM][HTTP-IN]"
                      {:remote-addr (:remote-addr ring-req)
                       :request (summarize-agent-request request-data)})
            (run-agent-stream request-data))
          (catch Exception e
            (log/error e "[AGENT][STREAM][HTTP-ERROR]"
                       {:remote-addr (:remote-addr ring-req) :uri uri})
            (json-response {:error (str "Stream failed: " (.getMessage e))})))
        (json-response {:error "Method not allowed. Use POST."}))

      "/api/agent/run-status"
      (let [run-id (get query-params "run-id")]
        (if (str/blank? run-id)
          (json-response {:error "Missing run-id parameter"})
          (if-let [run (get @!agent-runs run-id)]
            (json-response run)
            (json-response {:status :not-found :run-id run-id}))))

      ;; Not an API route — pass through
      (next-handler ring-req))))

(defn http-middleware [config]
  ;; these compose as functions, so are applied bottom up
  (-> not-found-handler
    (wrap-index-page config) ; 5. otherwise fallback to default page file
    (wrap-resource (:resources-path config)) ; 4. serve static file from classpath
    (wrap-content-type) ; 3. detect content (e.g. for index.html)
    (wrap-file-api) ; 2. intercept /api/* routes for file explorer
    (wrap-params))) ; 1. parse query params for API routes


(defn middleware [config entrypoint]
  (-> (http-middleware config)  ; 2. otherwise, serve regular http content
    (electric-websocket-middleware config entrypoint))) ; 1. intercept websocket upgrades and maybe start Electric

(defn- add-gzip-handler!
  "Makes Jetty server compress responses. Optional but recommended."
  [server]
  (.setHandler server
    (doto (GzipHandler.)
      #_(.setIncludedMimeTypes (into-array ["text/css" "text/plain" "text/javascript" "application/javascript" "application/json" "image/svg+xml"])) ; only compress these
      (.setMinGzipSize 1024)
      (.setHandler (.getHandler server)))))

(defn- configure-websocket!
  "Tune Jetty Websocket config for Electric compat." [server]
  (JettyWebSocketServletContainerInitializer/configure
    (.getHandler server)
    (reify JettyWebSocketServletContainerInitializer$Configurator
      (accept [_this _servletContext wsContainer]
        (.setIdleTimeout wsContainer (java.time.Duration/ofSeconds 60))
        (.setMaxBinaryMessageSize wsContainer (* 100 1024 1024)) ; 100M - temporary
        (.setMaxTextMessageSize wsContainer (* 100 1024 1024))))))   ; 100M - temporary


(defn start-server! [entrypoint
                     {:keys [port host]
                      :or   {port 8080, host "0.0.0.0"}
                      :as   config}]
  (let [server     (ring/run-jetty (middleware config entrypoint)
                     (merge {:port         port
                             :join?        false
                             :configurator (fn [server]
                                             (configure-websocket! server)
                                             (add-gzip-handler! server))}
                       config))]
    (log/info "👉" (str "http://" host ":" (-> server (.getConnectors) first (.getPort))))
    server))
