#!/usr/bin/env python3
"""Extract all of Sid's user messages (Claude Code + Codex CLI, Softland only)
into one chronological corpus: messages.jsonl + messages-chronological.md +
stats.txt + chunk files for agent fan-out.

Dedup strategy:
- Claude: resumed/compacted sessions copy history into new files. Dedup by
  message uuid first, then by sha1(ts + normalized text).
- Codex: user text appears both as event_msg/user_message (clean, primary)
  and response_item role:user (includes env wrappers; replayed history in
  resumed sessions appears ONLY here). Take event_msg always; take
  response_item only if not wrapper-prefixed and not already seen.
- Short messages ("continue", "yes") repeat legitimately: global text-hash
  dedup applies only to texts > 80 chars; short ones key on
  (session, hash, minute-bucket).
"""
import json, glob, hashlib, re, os, sys
from collections import Counter, defaultdict
from datetime import datetime, timezone

CLAUDE_DIR = '/home/sid/.claude/projects/-mnt-data-projects-Softland'
CODEX_GLOB = '/home/sid/.codex/sessions/2026/*/*/rollout-*.jsonl'
OUT_DIR = '/mnt/data/projects/Softland/docs/plans/fable-window-2026-06/data'

WRAPPER_PREFIXES = (
    '# AGENTS.md', '<environment_context>', '<user_instructions>',
    '<INSTRUCTIONS>', '<turn_aborted>', '<ENVIRONMENT', '# CLAUDE.md',
)
SYS_REMINDER_RE = re.compile(r'<system-reminder>.*?</system-reminder>', re.DOTALL)
CMD_NAME_RE = re.compile(r'<command-name>(.*?)</command-name>', re.DOTALL)
CMD_ARGS_RE = re.compile(r'<command-args>(.*?)</command-args>', re.DOTALL)
CMD_MSG_RE = re.compile(r'<command-message>.*?</command-message>', re.DOTALL)
IMAGE_TOKEN_RE = re.compile(r'\[Image[ #:][^\]]*\]')
CARET_CAVEAT = 'Caveat: The messages below were generated by the user while running local commands'

def norm_for_hash(text):
    t = IMAGE_TOKEN_RE.sub('', text)
    return re.sub(r'\s+', ' ', t).strip().lower()

def minute_bucket(ts):
    return ts[:16]  # YYYY-MM-DDTHH:MM

class Dedup:
    def __init__(self):
        self.uuids = set()
        self.long_hashes = set()
        self.short_keys = set()
        self.drops = Counter()
    def admit(self, text, ts, session, uuid=None):
        if uuid:
            if uuid in self.uuids:
                self.drops['uuid'] += 1; return False
            self.uuids.add(uuid)
        h = hashlib.sha1(norm_for_hash(text).encode()).hexdigest()
        if len(text) > 80:
            key = h
            if key in self.long_hashes:
                self.drops['long-hash'] += 1; return False
            self.long_hashes.add(key)
        else:
            key = (session, h, minute_bucket(ts))
            if key in self.short_keys:
                self.drops['short-key'] += 1; return False
            self.short_keys.add(key)
        return True

def read_claude(dedup):
    msgs = []
    skipped = Counter()
    for f in sorted(glob.glob(os.path.join(CLAUDE_DIR, '*.jsonl'))):
        for line in open(f):
            try: d = json.loads(line)
            except json.JSONDecodeError: continue
            if d.get('type') != 'user' or d.get('isSidechain'): continue
            msg = d.get('message', {})
            if msg.get('role') != 'user': continue
            c = msg.get('content')
            if isinstance(c, str):
                text = c
            elif isinstance(c, list):
                parts = [b.get('text', '') for b in c
                         if isinstance(b, dict) and b.get('type') == 'text']
                if not parts:
                    skipped['tool-result-only'] += 1; continue
                text = '\n'.join(parts)
            else:
                continue
            ts = d.get('timestamp', '')
            if not ts: skipped['no-ts'] += 1; continue
            kind = 'prompt'
            if '<command-name>' in text:
                name = CMD_NAME_RE.search(text)
                args = CMD_ARGS_RE.search(text)
                cmd = (name.group(1).strip() if name else '').strip()
                arg = (args.group(1).strip() if args else '').strip()
                text = f'{cmd} {arg}'.strip()
                kind = 'slash'
                if not text: skipped['empty-cmd'] += 1; continue
            if '<local-command-stdout>' in text:
                skipped['cmd-stdout'] += 1; continue
            text = SYS_REMINDER_RE.sub('', text)
            text = CMD_MSG_RE.sub('', text).strip()
            if text.startswith(CARET_CAVEAT):
                skipped['caveat-wrapper'] += 1; continue
            if re.fullmatch(r'\[Request interrupted[^\]]*\]', text):
                skipped['interrupt-stub'] += 1; continue
            if not text:
                skipped['empty'] += 1; continue
            session = (d.get('sessionId') or os.path.basename(f)[:8])[:8]
            if not dedup.admit(text, ts, session, uuid=d.get('uuid')):
                continue
            msgs.append({'ts': ts, 'source': 'claude', 'session': session,
                         'kind': kind, 'text': text})
    return msgs, skipped

def read_codex(dedup):
    msgs = []
    skipped = Counter()
    n_softland_files = 0
    for f in sorted(glob.glob(CODEX_GLOB)):
        try:
            first = json.loads(open(f).readline())
        except (json.JSONDecodeError, StopIteration): continue
        meta = first.get('payload', {})
        if first.get('type') != 'session_meta': continue
        if 'softland' not in meta.get('cwd', '').lower():
            skipped['other-project-file'] += 1; continue
        n_softland_files += 1
        session = (meta.get('id') or os.path.basename(f))[-8:]
        for line in open(f):
            try: d = json.loads(line)
            except json.JSONDecodeError: continue
            p = d.get('payload', {})
            ts = d.get('timestamp', '')
            if not ts: continue
            text = None
            if d.get('type') == 'event_msg' and p.get('type') == 'user_message':
                text = p.get('message', '')
            elif (d.get('type') == 'response_item' and p.get('type') == 'message'
                  and p.get('role') == 'user'):
                parts = [b.get('text', '') for b in p.get('content', [])
                         if isinstance(b, dict) and b.get('type') == 'input_text']
                cand = '\n'.join(parts).strip()
                if not cand: continue
                if cand.startswith(WRAPPER_PREFIXES):
                    skipped['wrapper'] += 1; continue
                # only as recovery for replayed history not seen via event_msg
                text = cand
            if text is None: continue
            text = IMAGE_TOKEN_RE.sub('', text).strip()
            if not text: skipped['empty'] += 1; continue
            kind = 'slash' if text.startswith('/') and len(text.split()[0]) > 1 else 'prompt'
            if not dedup.admit(text, ts, session):
                continue
            msgs.append({'ts': ts, 'source': 'codex', 'session': session,
                         'kind': kind, 'text': text})
    skipped['softland-files'] = n_softland_files
    return msgs, skipped

def main():
    os.makedirs(os.path.join(OUT_DIR, 'chunks'), exist_ok=True)
    os.makedirs(os.path.join(OUT_DIR, 'summaries'), exist_ok=True)
    dedup = Dedup()
    claude_msgs, claude_skip = read_claude(dedup)
    codex_msgs, codex_skip = read_codex(dedup)
    all_msgs = sorted(claude_msgs + codex_msgs, key=lambda m: m['ts'])
    counters = {'claude': 0, 'codex': 0}
    prefix = {'claude': 'C', 'codex': 'X'}
    for m in all_msgs:
        counters[m['source']] += 1
        m['id'] = f"{prefix[m['source']]}-{counters[m['source']]:04d}"
        m['n_chars'] = len(m['text'])

    with open(os.path.join(OUT_DIR, 'messages.jsonl'), 'w') as out:
        for m in all_msgs:
            out.write(json.dumps(m, ensure_ascii=False) + '\n')

    # readable chronological markdown
    with open(os.path.join(OUT_DIR, 'messages-chronological.md'), 'w') as out:
        out.write('# All user messages, chronological (Softland, Claude + Codex)\n')
        out.write(f'# Range: {all_msgs[0]["ts"]} -> {all_msgs[-1]["ts"]} | {len(all_msgs)} messages\n\n')
        cur_day = None; cur_sess = None
        for m in all_msgs:
            day = m['ts'][:10]
            if day != cur_day:
                dow = datetime.fromisoformat(m['ts'].replace('Z', '+00:00')).strftime('%a')
                out.write(f'\n## {day} ({dow})\n\n')
                cur_day = day; cur_sess = None
            sess = (m['source'], m['session'])
            if sess != cur_sess:
                out.write(f'--- session: {m["source"]} {m["session"]} ---\n\n')
                cur_sess = sess
            t = m['ts'][11:16] + 'Z'
            tag = ' /slash' if m['kind'] == 'slash' else ''
            out.write(f'**{m["id"]} · {t} [{m["source"]}{tag}]**\n{m["text"]}\n\n')

    # stats
    by_month = Counter((m['ts'][:7], m['source']) for m in all_msgs)
    by_session = Counter((m['source'], m['session']) for m in all_msgs)
    lengths = sorted(m['n_chars'] for m in all_msgs)
    def pct(p): return lengths[int(p * (len(lengths) - 1))]
    with open(os.path.join(OUT_DIR, 'stats.txt'), 'w') as out:
        out.write(f'total: {len(all_msgs)}  claude: {len(claude_msgs)}  codex: {len(codex_msgs)}\n')
        out.write(f'range: {all_msgs[0]["ts"]} -> {all_msgs[-1]["ts"]}\n')
        out.write(f'distinct sessions: claude {len({s for s in by_session if s[0]=="claude"})}, '
                  f'codex {len({s for s in by_session if s[0]=="codex"})}\n')
        out.write(f'dedup drops: {dict(dedup.drops)}\n')
        out.write(f'claude skipped: {dict(claude_skip)}\n')
        out.write(f'codex skipped: {dict(codex_skip)}\n')
        out.write(f'len p50/p90/p99/max: {pct(.5)}/{pct(.9)}/{pct(.99)}/{lengths[-1]}\n')
        out.write('\nper-month per-source:\n')
        for (mo, src), n in sorted(by_month.items()):
            out.write(f'  {mo} {src}: {n}\n')
        out.write('\nmessages per session (top 30):\n')
        for (src, s), n in by_session.most_common(30):
            out.write(f'  {src} {s}: {n}\n')

    # chunks: ~equal count, snap to session boundaries within +/-15 msgs
    N_CHUNKS = 12
    target = len(all_msgs) / N_CHUNKS
    boundaries = [0]
    for i in range(1, N_CHUNKS):
        ideal = round(i * target)
        best = ideal
        for off in range(0, 16):
            for cand in (ideal + off, ideal - off):
                if 0 < cand < len(all_msgs) and \
                   (all_msgs[cand]['source'], all_msgs[cand]['session']) != \
                   (all_msgs[cand-1]['source'], all_msgs[cand-1]['session']):
                    best = cand; break
            else:
                continue
            break
        boundaries.append(max(best, boundaries[-1] + 1))
    boundaries.append(len(all_msgs))

    for ci in range(N_CHUNKS):
        part = all_msgs[boundaries[ci]:boundaries[ci+1]]
        if not part: continue
        sessions = sorted({f'{m["source"]}:{m["session"]}' for m in part})
        path = os.path.join(OUT_DIR, 'chunks', f'chunk-{ci+1:02d}.md')
        with open(path, 'w') as out:
            out.write(f'# Chunk {ci+1:02d}/{N_CHUNKS}\n')
            out.write(f'Date range: {part[0]["ts"][:10]} -> {part[-1]["ts"][:10]} | '
                      f'{len(part)} messages | sessions: {", ".join(sessions)}\n')
            out.write('Format: **ID · time [source]** then the message text. '
                      'IDs are citation currency.\n\n')
            cur_day = None; cur_sess = None
            for m in part:
                day = m['ts'][:10]
                if day != cur_day:
                    out.write(f'\n## {day}\n\n'); cur_day = day; cur_sess = None
                sess = (m['source'], m['session'])
                if sess != cur_sess:
                    out.write(f'--- session: {m["source"]} {m["session"]} ---\n\n')
                    cur_sess = sess
                text = m['text']
                if m['n_chars'] > 2500:
                    text = text[:2500] + f'\n[truncated: {m["n_chars"]} chars total — full text in messages.jsonl id {m["id"]}]'
                tag = ' /slash' if m['kind'] == 'slash' else ''
                out.write(f'**{m["id"]} · {m["ts"][11:16]}Z [{m["source"]}{tag}]**\n{text}\n\n')

    print(open(os.path.join(OUT_DIR, 'stats.txt')).read())
    print('chunk boundaries:', boundaries)

if __name__ == '__main__':
    main()
